import Link from "next/link";

const logos = [["HCL", "/assets/clients/w-hcl.png"], ["Hexaware", "/assets/clients/w-hexaware.png"], ["Genpact", "/assets/clients/w-genpact.png"], ["Persistent", "/assets/clients/w-persistent.png"], ["Synechron", "/assets/clients/w-synechron.png"], ["Saama", "/assets/clients/w-saama.png"], ["InfoVision", "/assets/clients/w-infovision.png"], ["VibrantCare", "/assets/clients/w-vibrantcare.png"]];
const services = [["01", "Staffing", "Contract, contract-to-hire and direct placement for teams that need talent without the noise."], ["02", "Professional recruitment", "Specialist search across technology, finance, healthcare, legal, operations and more."], ["03", "Executive search", "Confidential leadership searches built around context, market intelligence and fit."], ["04", "RPO & talent acquisition", "Recruiting capacity that works as an extension of your team, not another vendor layer."], ["05", "Workforce solutions", "Flexible talent programs for complex, changing and distributed workforces."], ["06", "VMS-enabled delivery", "Structured contingent workforce operations backed by disciplined processes and visibility."]];
const industries = ["Technology", "Financial Services", "Healthcare", "Legal", "Aerospace & Defense", "Telecommunications", "Manufacturing", "Supply Chain", "Sales & Marketing"];
const faqs = [["What does Rivago do?", "Rivago is a global staffing and recruitment company helping organizations find, evaluate and hire talent across technology, finance, healthcare, legal, operations and other specialist functions."], ["Where does Rivago operate?", "Our recruiting operations serve clients and talent across the United States, Canada, the UAE and India."], ["Do you support permanent and contract hiring?", "Yes. We support direct hire, contract, contract-to-hire, interim and broader workforce engagements depending on the client requirement."], ["How is Rivago using technology and AI?", "We use technology to make recruiting more informed and efficient, while developing a longer-term intelligence layer around sourcing, screening, matching and hiring workflows. We only present capabilities as live products when they are actually available."]];
const jsonLd = { "@context": "https://schema.org", "@type": ["Organization", "EmploymentAgency"], name: "Rivago Infotech", alternateName: "Rivago", url: "https://rivagoinfotech.com", logo: "https://rivagoinfotech.com/assets/og-image.png", description: "Rivago is a technology-powered talent company combining recruiting expertise with intelligent technology to help organizations find, evaluate and hire exceptional talent.", email: "info@rivagoinfotech.com", telephone: "+1-888-508-5703", areaServed: ["United States", "Canada", "United Arab Emirates", "India"], sameAs: ["https://www.linkedin.com/company/rivago-infotech-inc", "https://www.instagram.com/rivago.official/"] };
function Arrow() { return <span aria-hidden="true">↗</span>; }

export default function Home() {
  return <main className="rv-home">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

    <section className="rv-hero">
      <div className="rv-hero-grid" aria-hidden="true" /><div className="rv-hero-glow rv-glow-a" aria-hidden="true" /><div className="rv-hero-glow rv-glow-b" aria-hidden="true" />
      <div className="rv-hero-content">
        <div className="rv-kicker gs"><span className="rv-live-dot" /> Technology-powered talent · US · Canada · UAE · India</div>
        <h1 className="rv-display gs">Talent,<br /><em>amplified</em> by intelligence.</h1>
        <p className="rv-hero-copy gs">Rivago combines recruiting expertise, market intelligence and technology to help ambitious companies find, evaluate and hire exceptional people.</p>
        <div className="rv-actions gs"><button className="rv-btn rv-btn-primary" data-help>Hire talent <Arrow /></button><a className="rv-btn rv-btn-ghost" href="#intelligence">Explore Rivago <Arrow /></a></div>
        <div className="rv-proof gs"><span>Built for modern hiring</span><i /><span>Human expertise</span><i /><span>Intelligent technology</span></div>
      </div>
      <div className="rv-hero-visual gs" aria-label="Illustration of Rivago's talent intelligence workflow">
        <div className="rv-orbit rv-orbit-1" /><div className="rv-orbit rv-orbit-2" /><div className="rv-orbit rv-orbit-3" />
        <div className="rv-core"><span>R</span><small>RIVAGO<br />INTELLIGENCE</small></div>
        <div className="rv-node rv-node-1"><b>ROLE</b><span>Senior Product Engineer</span></div><div className="rv-node rv-node-2"><b>TALENT</b><span>Market signals</span></div><div className="rv-node rv-node-3"><b>SCREEN</b><span>Context + fit</span></div><div className="rv-node rv-node-4"><b>SHORTLIST</b><span>Human reviewed</span></div>
        <div className="rv-scan"><span /><strong>Live intelligence layer</strong><small>Mapping the right signals to the right search</small></div>
      </div><div className="rv-scroll">Scroll to explore <span>↓</span></div>
    </section>

    <section className="rv-trust"><div className="rv-container"><div className="rv-trust-label">Teams that trust Rivago with critical talent</div><div className="rv-logo-row">{logos.map(([name, src]) => <div className="rv-logo" key={name}><img src={src} alt={name} /></div>)}</div></div></section>

    <section className="rv-problem"><div className="rv-container rv-problem-grid"><div><div className="rv-eyebrow gs">01 · The hiring problem</div><h2 className="rv-heading gs">Hiring isn't a volume problem.<br /><em>It's a signal problem.</em></h2></div><div className="rv-problem-copy gs"><p>More profiles don't automatically create better hiring decisions. The challenge is separating relevant talent from everything that looks relevant.</p><p>That's where Rivago brings together people, process and technology — so your team spends less time sorting and more time deciding.</p></div></div><div className="rv-signal" aria-label="Illustrative hiring signal funnel">{[["10,000", "profiles"], ["1,240", "relevant signals"], ["184", "qualified"], ["32", "reviewed"], ["8", "shortlisted"], ["1", "right hire"]].map(([num, label]) => <div className="rv-signal-step gs" key={label}><strong>{num}</strong><span>{label}</span></div>)}</div><div className="rv-illustrative">Illustrative workflow — not a representation of live platform data.</div></section>

    <section className="rv-intelligence" id="intelligence"><div className="rv-container"><div className="rv-eyebrow gs">02 · Rivago intelligence</div><div className="rv-intel-head"><h2 className="rv-heading rv-heading-light gs">Technology finds the signal.<br /><em>People understand the context.</em></h2><p className="rv-body-light gs">We're building technology around the recruiting problems we understand firsthand. The goal isn't to replace judgment — it's to give good judgment better information.</p></div><div className="rv-intel-flow">{["Discover", "Understand", "Evaluate", "Match", "Decide"].map((item, i) => <div className="rv-intel-step gs" key={item}><span>0{i + 1}</span><b>{item}</b><small>{["Find relevant talent", "Read the context", "Surface useful signals", "Connect role + person", "Make the call"][i]}</small>{i < 4 && <i aria-hidden="true">→</i>}</div>)}</div><div className="rv-intel-note gs"><span>BUILDING</span><p>Rivago's technology direction spans intelligent sourcing, screening, matching and recruiting workflows. Future products will be introduced as they become real, tested and ready.</p></div></div></section>

    <section className="rv-human"><div className="rv-container rv-human-grid"><div className="rv-human-statement gs"><div className="rv-eyebrow">03 · The Rivago difference</div><h2 className="rv-heading">AI can process the signal.<br /><em>Hiring still needs people.</em></h2></div><div className="rv-human-list">{[["Technology", "Search, data, matching, screening, automation"], ["Recruiters", "Context, judgment, relationships, culture"], ["Together", "Faster decisions without losing the human bar"]].map(([title, desc], i) => <div className="rv-human-row gs" key={title}><span>0{i + 1}</span><div><b>{title}</b><p>{desc}</p></div><span aria-hidden="true">↗</span></div>)}</div></div></section>

    <section className="rv-process"><div className="rv-container"><div className="rv-eyebrow gs">04 · How we work</div><div className="rv-process-head"><h2 className="rv-heading rv-heading-light gs">From brief to <em>better decisions.</em></h2><p className="rv-body-light gs">A disciplined search process, owned end to end by people who understand the market.</p></div><div className="rv-process-grid">{[["01", "Understand", "Calibrate the role, hiring bar, context and constraints before sourcing begins."], ["02", "Map", "Open the search across direct sourcing, referrals, networks and relevant talent markets."], ["03", "Screen", "Assess capability, motivation, availability and fit before candidates reach your team."], ["04", "Calibrate", "Bring recruiter judgment and client feedback together to sharpen the search."], ["05", "Match", "Present a focused shortlist with the context needed to make a confident decision."], ["06", "Hire", "Support offer, transition and the relationship after the candidate starts."]].map(([num, title, desc]) => <article className="rv-process-card gs" key={num}><span>{num}</span><h3>{title}</h3><p>{desc}</p><span aria-hidden="true">↗</span></article>)}</div></div></section>

    <section className="rv-services"><div className="rv-container"><div className="rv-eyebrow gs">05 · Talent solutions</div><div className="rv-section-head"><h2 className="rv-heading gs">Built around the way<br /><em>you actually hire.</em></h2><Link href="/services" className="rv-text-link gs">View all services <Arrow /></Link></div><div className="rv-service-grid">{services.map(([num, title, desc]) => <Link href="/services" className="rv-service-card gs" key={num}><span>{num}</span><h3>{title}</h3><p>{desc}</p><span aria-hidden="true">↗</span></Link>)}</div></div></section>

    <section className="rv-industries"><div className="rv-container"><div className="rv-eyebrow gs">06 · Industries</div><div className="rv-section-head"><h2 className="rv-heading rv-heading-light gs">Deep expertise where<br /><em>talent matters most.</em></h2><p className="rv-body-light gs">Specialist recruiting across the sectors, functions and markets where the right hire changes the outcome.</p></div><div className="rv-industry-grid">{industries.map((item, i) => <Link href="/industries" key={item} className="rv-industry gs"><span>0{i + 1}</span><b>{item}</b><span aria-hidden="true">↗</span></Link>)}</div></div></section>

    <section className="rv-proof-section"><div className="rv-container"><div className="rv-eyebrow gs">07 · Proof</div><div className="rv-section-head"><h2 className="rv-heading gs">Real recruiting work.<br /><em>Real outcomes.</em></h2><Link href="/resources" className="rv-text-link gs">Explore insights <Arrow /></Link></div><div className="rv-case-grid"><Link href="/resources" className="rv-case rv-case-large gs"><div className="rv-case-art"><span>CASE STUDY</span><strong>Technology</strong><div className="rv-case-lines" /></div><div className="rv-case-copy"><small>Technology · North America</small><h3>Scaling critical teams without scaling the hiring noise.</h3><p>Explore how a focused, context-led search changed the shape of a fast-moving technology hiring program.</p><span aria-hidden="true">↗</span></div></Link><Link href="/resources" className="rv-case gs"><div className="rv-case-art rv-case-art-alt"><span>CASE STUDY</span><strong>Healthcare</strong></div><div className="rv-case-copy"><small>Healthcare · UAE</small><h3>Specialist talent for a complex expansion.</h3><p>A disciplined search process built around specialist requirements and compliance.</p><span aria-hidden="true">↗</span></div></Link><Link href="/resources" className="rv-case gs"><div className="rv-case-art rv-case-art-third"><span>INSIGHT</span><strong>Talent intelligence</strong></div><div className="rv-case-copy"><small>Rivago Intelligence</small><h3>What changes when recruiters have better signals?</h3><p>Our perspective on where AI can make recruiting more useful, not just more automated.</p><span aria-hidden="true">↗</span></div></Link></div><div className="rv-proof-disclaimer">Selected examples are presented for the new brand experience. Publish client names, metrics and detailed outcomes only after commercial verification and approval.</div></div></section>

    <section className="rv-faq"><div className="rv-container rv-faq-grid"><div><div className="rv-eyebrow gs">08 · FAQ</div><h2 className="rv-heading rv-heading-light gs">Questions before<br /><em>we get started.</em></h2></div><div className="rv-faq-list">{faqs.map(([q, a], i) => <details className="rv-faq-item gs" key={q}><summary><span>0{i + 1}</span>{q}<b>+</b></summary><p>{a}</p></details>)}</div></div></section>

    <section className="rv-cta"><div className="rv-cta-grid" aria-hidden="true" /><div className="rv-cta-content"><div className="rv-eyebrow gs">09 · Start a conversation</div><h2 className="rv-cta-heading gs">The right hire<br /><em>changes everything.</em></h2><p className="gs">Tell us what you're building. We'll help you find the people to build it.</p><div className="rv-actions gs"><button className="rv-btn rv-btn-primary" data-help>Talk to Rivago <Arrow /></button><Link href="/view-jobs" className="rv-btn rv-btn-ghost">Explore opportunities <Arrow /></Link></div></div></section>
  </main>;
}
