import Link from "next/link";

const logos = [["HCL", "/assets/clients/w-hcl.png"], ["Hexaware", "/assets/clients/w-hexaware.png"], ["Genpact", "/assets/clients/w-genpact.png"], ["Persistent", "/assets/clients/w-persistent.png"], ["Synechron", "/assets/clients/w-synechron.png"], ["Saama", "/assets/clients/w-saama.png"], ["InfoVision", "/assets/clients/w-infovision.png"], ["VibrantCare", "/assets/clients/w-vibrantcare.png"]];
const capabilities = [
  ["01", "Direct Hire", "Permanent hiring for critical roles, built around the business context behind the requisition."],
  ["02", "Contract Staffing", "Flexible technology and professional talent for teams that need speed without sacrificing quality."],
  ["03", "Executive Search", "Confidential leadership searches shaped by market intelligence, judgment and long-term fit."],
  ["04", "RPO & Talent Acquisition", "An extension of your recruiting operation with consistent process, ownership and visibility."],
  ["05", "Workforce Solutions", "Structured talent programs for changing workforce requirements and distributed teams."],
  ["06", "VMS-Enabled Delivery", "Disciplined contingent workforce delivery designed for visibility, compliance and control."]
];
const industries = ["Technology & SaaS", "Financial Services", "Healthcare & Life Sciences", "Engineering & Manufacturing", "Telecommunications", "Supply Chain & Logistics", "Professional Services", "Sales & Marketing"];
const faqs = [
  ["What does Rivago do?", "Rivago is a global staffing and recruitment company helping organizations find, evaluate and hire talent across technology, finance, healthcare, legal, operations and specialist functions."],
  ["Where does Rivago operate?", "Our recruiting operations serve clients and talent across the United States, Canada, the UAE and India."],
  ["Do you support permanent and contract hiring?", "Yes. We support direct hire, contract, contract-to-hire, interim and broader workforce engagements based on the requirement."],
  ["How is Rivago using technology and AI?", "We use technology to make recruiting more informed and efficient while building an intelligence layer around sourcing, screening, matching and hiring workflows. We only present capabilities as live products when they are actually available."]
];
const jsonLd = { "@context": "https://schema.org", "@type": ["Organization", "EmploymentAgency"], name: "Rivago Infotech", alternateName: "Rivago", url: "https://rivagoinfotech.com", logo: "https://rivagoinfotech.com/assets/og-image.png", description: "Rivago is a technology-powered talent company combining recruiting expertise with intelligent technology to help organizations find, evaluate and hire exceptional talent.", email: "info@rivagoinfotech.com", telephone: "+1-888-508-5703", areaServed: ["United States", "Canada", "United Arab Emirates", "India"] };

const Arrow = () => <span aria-hidden="true">↗</span>;

export default function Home() {
  return <main className="rv-home">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

    <section className="rv-hero rv-editorial-dark">
      <div className="rv-container rv-hero-inner">
        <div className="rv-hero-meta gs"><span>RIVAGO INFOTECH</span><i /> Technology-powered talent</div>
        <div className="rv-hero-copy-wrap">
          <h1 className="rv-display gs">Build better teams.<br /><em>Move the business forward.</em></h1>
          <div className="rv-hero-side gs"><p>Rivago combines recruiting expertise, market intelligence and technology to help organizations find the people who make progress possible.</p><div className="rv-actions"><button className="rv-btn rv-btn-primary" data-help>Hire talent <Arrow /></button><Link className="rv-btn rv-btn-ghost" href="/view-jobs">Explore opportunities <Arrow /></Link></div></div>
        </div>
        <div className="rv-hero-bottom gs"><span>US · CANADA · UAE · INDIA</span><span>STAFFING · RECRUITMENT · WORKFORCE SOLUTIONS</span><span>01 — 09</span></div>
      </div>
    </section>

    <section className="rv-trust rv-light"><div className="rv-container"><div className="rv-trust-top"><span>Trusted talent partner</span><span>Selected client relationships</span></div><div className="rv-logo-row">{logos.map(([name, src]) => <div className="rv-logo" key={name}><img src={src} alt={name} /></div>)}</div></div></section>

    <section className="rv-problem rv-light"><div className="rv-container"><div className="rv-section-marker gs">01 <span>/</span> The challenge</div><div className="rv-editorial-intro"><h2 className="rv-heading gs">Hiring has changed.<br /><em>The old way hasn't.</em></h2><div className="rv-intro-copy gs"><p>More applications, more vendors and more technology do not automatically create better hiring decisions.</p><p>The hard part is still the same: understanding what matters, finding the right signal and making a confident decision before the opportunity moves.</p></div></div><div className="rv-statements"><article className="rv-statement gs"><span>01</span><h3>Disconnected signals</h3><p>Resumes, interviews, market data and hiring feedback often live in separate workflows.</p></article><article className="rv-statement gs"><span>02</span><h3>Slow decisions</h3><p>Volume creates work. It does not create clarity. Strong candidates can disappear inside the process.</p></article><article className="rv-statement gs"><span>03</span><h3>Human context matters</h3><p>Skills are measurable. Motivation, environment, leadership and fit still require judgment.</p></article></div></div></section>

    <section className="rv-intelligence rv-dark" id="intelligence"><div className="rv-container"><div className="rv-section-marker rv-marker-light gs">02 <span>/</span> Rivago Intelligence</div><div className="rv-intel-intro"><h2 className="rv-heading rv-heading-light gs">Turn recruiting signals<br /><em>into better decisions.</em></h2><p className="rv-body-light gs">We are building technology around the recruiting problems we understand firsthand — making search, evaluation and matching more informed without removing human accountability.</p></div><div className="rv-intel-architecture gs"><div><span>01</span><b>DISCOVER</b><small>Relevant talent markets</small></div><i>→</i><div><span>02</span><b>UNDERSTAND</b><small>Role + candidate context</small></div><i>→</i><div><span>03</span><b>EVALUATE</b><small>Skills + useful signals</small></div><i>→</i><div><span>04</span><b>MATCH</b><small>Role + person + fit</small></div><i>→</i><div><span>05</span><b>DECIDE</b><small>Human-reviewed shortlist</small></div></div><div className="rv-building gs"><strong>BUILDING</strong><p>Our technology direction spans intelligent sourcing, screening, matching and recruiting workflows. Future products will be introduced as they become real, tested and ready.</p></div></div></section>

    <section className="rv-method rv-light"><div className="rv-container"><div className="rv-section-marker gs">03 <span>/</span> Our method</div><div className="rv-editorial-intro"><h2 className="rv-heading gs">A recruiting process<br /><em>built for clarity.</em></h2><p className="rv-intro-copy gs">The best search is not the one with the most candidates. It is the one where every step makes the next decision easier.</p></div><div className="rv-method-grid">{[["01", "Define", "Calibrate the role, business context, success profile and constraints before the search begins."], ["02", "Discover", "Map relevant talent through direct sourcing, networks, referrals and market intelligence."], ["03", "Assess", "Evaluate capability, motivation, availability and fit before candidates reach your team."], ["04", "Calibrate", "Use recruiter judgment and client feedback to sharpen the search continuously."], ["05", "Present", "Deliver a focused shortlist with the context needed to make a confident decision."], ["06", "Deliver", "Support the process through offer, transition and the relationship after the hire."]].map(([n,t,d]) => <article className="rv-method-card gs" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><Arrow /></article>)}</div></div></section>

    <section className="rv-capabilities rv-cream"><div className="rv-container"><div className="rv-section-marker gs">04 <span>/</span> What we do</div><div className="rv-cap-head"><h2 className="rv-heading gs">Talent solutions<br /><em>with a point of view.</em></h2><Link href="/services" className="rv-text-link gs">Explore all capabilities <Arrow /></Link></div><div className="rv-cap-list">{capabilities.map(([n,t,d]) => <Link href="/services" className="rv-cap-row gs" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><Arrow /></Link>)}</div></div></section>

    <section className="rv-human rv-dark"><div className="rv-container"><div className="rv-section-marker rv-marker-light gs">05 <span>/</span> Human + technology</div><div className="rv-human-grid"><div><h2 className="rv-heading rv-heading-light gs">Technology can accelerate the search.<br /><em>People raise the bar.</em></h2></div><div className="rv-human-copy gs"><p>We do not believe great hiring is a choice between technology and people.</p><p>The advantage comes from knowing where each should lead: technology expands the signal; recruiters bring context, judgment and relationships.</p><div className="rv-principles"><div><span>01</span><b>Technology</b><small>Speed · signal · scale</small></div><div><span>02</span><b>Recruiters</b><small>Context · judgment · trust</small></div><div><span>03</span><b>Together</b><small>Better decisions · better outcomes</small></div></div></div></div></div></section>

    <section className="rv-industries rv-light"><div className="rv-container"><div className="rv-section-marker gs">06 <span>/</span> Where we work</div><div className="rv-cap-head"><h2 className="rv-heading gs">Built for teams where<br /><em>talent changes outcomes.</em></h2><p className="rv-intro-copy gs">Specialist recruiting across the sectors, functions and markets where the right hire matters.</p></div><div className="rv-industry-list">{industries.map((item,i) => <Link href="/industries" className="rv-industry-row gs" key={item}><span>0{i+1}</span><b>{item}</b><Arrow /></Link>)}</div></div></section>

    <section className="rv-proof rv-cream"><div className="rv-container"><div className="rv-section-marker gs">07 <span>/</span> Proof + perspective</div><div className="rv-proof-head"><h2 className="rv-heading gs">What we're learning<br /><em>from the market.</em></h2><Link href="/resources" className="rv-text-link gs">Explore Rivago Insights <Arrow /></Link></div><div className="rv-proof-grid"><Link href="/resources" className="rv-feature gs"><div className="rv-feature-art"><span>RIVAGO / INSIGHT 01</span><b>01</b></div><div><small>Talent intelligence</small><h3>What changes when recruiters have better signals?</h3><p>Our perspective on where intelligence can make recruiting more useful, not just more automated.</p><Arrow /></div></Link><Link href="/resources" className="rv-feature gs"><div className="rv-feature-art rv-feature-art-2"><span>RIVAGO / PERSPECTIVE 02</span><b>02</b></div><div><small>Workforce strategy</small><h3>Building a talent operation that can move with the business.</h3><p>Why process, ownership and market context matter as much as candidate volume.</p><Arrow /></div></Link></div><div className="rv-verification">Client names, metrics and detailed outcomes will be published only after commercial verification and approval.</div></div></section>

    <section className="rv-faq rv-dark"><div className="rv-container rv-faq-grid"><div><div className="rv-section-marker rv-marker-light gs">08 <span>/</span> FAQ</div><h2 className="rv-heading rv-heading-light gs">Before we<br /><em>get started.</em></h2></div><div className="rv-faq-list">{faqs.map(([q,a],i) => <details className="rv-faq-item gs" key={q}><summary><span>0{i+1}</span><b>{q}</b><i>+</i></summary><p>{a}</p></details>)}</div></div></section>

    <section className="rv-cta rv-editorial-dark"><div className="rv-container rv-cta-inner"><div className="rv-section-marker rv-marker-light gs">09 <span>/</span> Start a conversation</div><h2 className="rv-cta-heading gs">The right people<br /><em>move everything forward.</em></h2><div className="rv-cta-bottom gs"><p>Tell us what you're building, changing or scaling. We'll help you find the talent to move it forward.</p><div className="rv-actions"><button className="rv-btn rv-btn-primary" data-help>Talk to Rivago <Arrow /></button><Link className="rv-btn rv-btn-ghost" href="/view-jobs">Explore opportunities <Arrow /></Link></div></div></div></section>
  </main>;
}
