// Real client job-board data for the /view-jobs board, matching the Claude Design export.
// Ported verbatim from view-jobs.html (JOBS array + FAMTXT description templates).

export type Engagement = "Direct hire" | "Contract" | "Contract-to-hire";
export type WorkStyle = "Remote" | "On-Site" | "Hybrid";

export type BoardJob = {
  t: string;
  c: string;
  w: WorkStyle;
  e: Engagement;
  p: string;
  d: string;
  dept: string;
  f: string;
};

export const JOBS: BoardJob[] = [
  { t: "AI / LLM Engineer", c: "Austin, TX", w: "Remote", e: "Direct hire", p: "$219K", d: "2026-08-19", dept: "Technology", f: "ai" },
  { t: "Data Engineer", c: "Boston, MA", w: "Remote", e: "Contract", p: "$68/hr", d: "2026-08-20", dept: "Technology", f: "data" },
  { t: "Full-Stack Engineer", c: "Atlanta, GA", w: "Remote", e: "Direct hire", p: "$142K", d: "2026-08-18", dept: "Technology", f: "fullstack" },
  { t: "Backend Engineer", c: "Phoenix, AZ", w: "Remote", e: "Contract-to-hire", p: "$92/hr", d: "2026-08-19", dept: "Technology", f: "backend" },
  { t: "Frontend Engineer", c: "Columbus, OH", w: "On-Site", e: "Contract", p: "$89/hr", d: "2026-08-17", dept: "Technology", f: "frontend" },
  { t: "DevOps Engineer", c: "Tampa, FL", w: "On-Site", e: "Contract", p: "$85/hr", d: "2026-08-18", dept: "Technology", f: "devops" },
  { t: "MLOps Engineer", c: "Cambridge, ON", w: "Remote", e: "Direct hire", p: "CAD 206K", d: "2026-08-17", dept: "Technology", f: "mlops" },
  { t: "Security Engineer", c: "Ottawa, ON", w: "Remote", e: "Contract", p: "CAD $78/hr", d: "2026-08-18", dept: "Technology", f: "security" },
  { t: "Cloud Engineer", c: "Abu Dhabi, UAE", w: "Hybrid", e: "Direct hire", p: "AED 55K/mo", d: "2026-08-15", dept: "Technology", f: "cloud" },
  { t: "iOS Engineer", c: "Columbus, OH", w: "On-Site", e: "Contract", p: "$370/day", d: "2026-08-15", dept: "Technology", f: "mobile" },
  { t: "QA Automation Engineer", c: "Raleigh, NC", w: "On-Site", e: "Contract", p: "$255/day", d: "2026-08-16", dept: "Technology", f: "qa" },
  { t: "Product Manager", c: "Bengaluru, India", w: "Hybrid", e: "Contract", p: "₹1905/day", d: "2026-08-14", dept: "Product", f: "pm" },
  { t: "Product Designer", c: "New York, NY", w: "Remote", e: "Contract-to-hire", p: "$82/hr", d: "2026-08-14", dept: "Design", f: "design" },
  { t: "Data Analyst", c: "Seattle, WA", w: "Hybrid", e: "Contract", p: "$71/hr", d: "2026-08-14", dept: "Technology", f: "analytics" },
  { t: "Clinical Data Manager", c: "Dallas, TX", w: "Hybrid", e: "Contract", p: "$79/hr", d: "2026-08-12", dept: "Healthcare", f: "clinical" },
  { t: "Regulatory Affairs Manager", c: "San Diego, CA", w: "Remote", e: "Contract-to-hire", p: "$76/hr", d: "2026-08-13", dept: "Healthcare", f: "regulatory" },
  { t: "Nurse Manager", c: "Nashville, TN", w: "Hybrid", e: "Contract", p: "$52/hr", d: "2026-08-12", dept: "Healthcare", f: "nursing" },
  { t: "Corporate Counsel", c: "Remote, US", w: "Remote", e: "Direct hire", p: "$149K", d: "2026-08-10", dept: "Legal", f: "legal" },
  { t: "Compliance Officer", c: "Vancouver, BC", w: "On-Site", e: "Contract", p: "CAD $78/hr", d: "2026-08-10", dept: "Finance", f: "compliance" },
  { t: "Financial Controller", c: "Remote, Canada", w: "Remote", e: "Contract-to-hire", p: "CAD $75/hr", d: "2026-08-09", dept: "Finance", f: "finance" },
  { t: "FP&A Analyst", c: "Wilmington, DE", w: "Hybrid", e: "Contract", p: "$355/day", d: "2026-08-09", dept: "Finance", f: "fpna" },
  { t: "HR Business Partner", c: "Calgary, AB", w: "Remote", e: "Direct hire", p: "$105K", d: "2026-08-10", dept: "People", f: "hr" },
  { t: "Technical Recruiter", c: "Remote, US", w: "Remote", e: "Contract-to-hire", p: "$430/day", d: "2026-08-09", dept: "People", f: "ta" },
  { t: "Supply Chain Analyst", c: "Hyderabad, India", w: "Remote", e: "Contract-to-hire", p: "₹1775/day", d: "2026-08-07", dept: "Operations", f: "supply" },
  { t: "Logistics Coordinator", c: "Chicago, IL", w: "Hybrid", e: "Contract", p: "$82/hr", d: "2026-08-06", dept: "Operations", f: "logistics" },
  { t: "Manufacturing Engineer", c: "Wilmington, DE", w: "Remote", e: "Contract-to-hire", p: "$88/hr", d: "2026-08-07", dept: "Operations", f: "mfg" },
  { t: "Account Executive", c: "Denver, CO", w: "Hybrid", e: "Contract-to-hire", p: "$60/hr", d: "2026-08-06", dept: "Sales & Marketing", f: "sales" },
  { t: "Demand Generation Manager", c: "Charlotte, NC", w: "On-Site", e: "Contract", p: "$80/hr", d: "2026-08-07", dept: "Sales & Marketing", f: "marketing" },
  { t: "Customer Success Manager", c: "Minneapolis, MN", w: "Hybrid", e: "Direct hire", p: "$104K", d: "2026-08-06", dept: "Sales & Marketing", f: "csm" },
  { t: "Talent Researcher", c: "Toronto, ON", w: "Remote", e: "Contract-to-hire", p: "CAD $78/hr", d: "2026-08-05", dept: "Research", f: "research" },
  { t: "Chief Technology Officer", c: "Calgary, AB", w: "On-Site", e: "Contract-to-hire", p: "CAD $236/hr", d: "2026-08-03", dept: "Executive", f: "exec" },
  { t: "Senior AI Engineer", c: "Dubai, UAE", w: "On-Site", e: "Direct hire", p: "AED 50K/mo", d: "2026-08-03", dept: "Technology", f: "ai" },
  { t: "Senior Data Engineer", c: "Pune, MH", w: "Hybrid", e: "Contract-to-hire", p: "$330/day", d: "2026-08-04", dept: "Technology", f: "data" },
  { t: "Senior Full-Stack Engineer", c: "Dubai, AE", w: "Hybrid", e: "Direct hire", p: "$105K", d: "2026-08-03", dept: "Technology", f: "fullstack" },
  { t: "Senior Backend Engineer (Java)", c: "Pune, India", w: "On-Site", e: "Contract-to-hire", p: "₹1765/day", d: "2026-08-02", dept: "Technology", f: "backend" },
  { t: "Senior Frontend Engineer (React)", c: "Austin, TX", w: "Remote", e: "Direct hire", p: "$128K", d: "2026-07-31", dept: "Technology", f: "frontend" },
  { t: "Senior DevOps Engineer", c: "Boston, MA", w: "Remote", e: "Direct hire", p: "$145K", d: "2026-08-02", dept: "Technology", f: "devops" },
  { t: "Senior MLOps Engineer", c: "Atlanta, GA", w: "Hybrid", e: "Contract-to-hire", p: "$112/hr", d: "2026-07-31", dept: "Technology", f: "mlops" },
  { t: "Senior Security Engineer — AppSec", c: "Phoenix, AZ", w: "Hybrid", e: "Direct hire", p: "$205K", d: "2026-07-30", dept: "Technology", f: "security" },
  { t: "Solutions Architect — Cloud", c: "Columbus, OH", w: "Remote", e: "Contract", p: "$102/hr", d: "2026-07-31", dept: "Technology", f: "cloud" },
  { t: "Senior Android Engineer", c: "Tampa, FL", w: "Remote", e: "Contract-to-hire", p: "$96/hr", d: "2026-07-29", dept: "Technology", f: "mobile" },
  { t: "Senior QA Engineer", c: "Cambridge, ON", w: "On-Site", e: "Contract-to-hire", p: "CAD $69/hr", d: "2026-07-28", dept: "Technology", f: "qa" },
  { t: "Senior Product Manager", c: "Ottawa, ON", w: "On-Site", e: "Contract-to-hire", p: "CAD $94/hr", d: "2026-07-27", dept: "Product", f: "pm" },
  { t: "Senior Product Designer", c: "Abu Dhabi, UAE", w: "Hybrid", e: "Contract", p: "AED 1250/day", d: "2026-07-29", dept: "Design", f: "design" },
  { t: "Senior Data Analyst", c: "Columbus, OH", w: "On-Site", e: "Direct hire", p: "$110K", d: "2026-07-27", dept: "Technology", f: "analytics" },
  { t: "Clinical Research Associate", c: "Raleigh, NC", w: "On-Site", e: "Contract", p: "$290/day", d: "2026-07-27", dept: "Healthcare", f: "clinical" },
  { t: "Regulatory Affairs Specialist", c: "Bengaluru, India", w: "On-Site", e: "Contract", p: "₹905/day", d: "2026-07-25", dept: "Healthcare", f: "regulatory" },
  { t: "Clinical Nurse Specialist", c: "New York, NY", w: "On-Site", e: "Contract-to-hire", p: "$51/hr", d: "2026-07-26", dept: "Healthcare", f: "nursing" },
  { t: "Senior Commercial Counsel", c: "Seattle, WA", w: "Remote", e: "Contract", p: "$79/hr", d: "2026-07-25", dept: "Legal", f: "legal" },
  { t: "Compliance Manager", c: "Dallas, TX", w: "On-Site", e: "Direct hire", p: "$104K", d: "2026-07-25", dept: "Finance", f: "compliance" },
  { t: "Assistant Controller", c: "San Diego, CA", w: "Remote", e: "Direct hire", p: "$165K", d: "2026-07-23", dept: "Finance", f: "finance" },
  { t: "FP&A Manager", c: "Nashville, TN", w: "Remote", e: "Contract", p: "$52/hr", d: "2026-07-23", dept: "Finance", f: "fpna" },
  { t: "Senior HR Business Partner", c: "Remote, US", w: "Remote", e: "Contract-to-hire", p: "$55/hr", d: "2026-07-23", dept: "People", f: "hr" },
  { t: "Senior Technical Recruiter", c: "Vancouver, BC", w: "Remote", e: "Direct hire", p: "CAD 222K", d: "2026-07-23", dept: "People", f: "ta" },
  { t: "Supply Chain Manager", c: "Remote, Canada", w: "Remote", e: "Contract-to-hire", p: "CAD $75/hr", d: "2026-07-21", dept: "Operations", f: "supply" },
  { t: "Logistics Manager", c: "Wilmington, DE", w: "Hybrid", e: "Direct hire", p: "$100K", d: "2026-07-22", dept: "Operations", f: "logistics" },
  { t: "Process Engineer", c: "Calgary, AB", w: "Hybrid", e: "Contract-to-hire", p: "$370/day", d: "2026-07-22", dept: "Operations", f: "mfg" },
  { t: "Senior Account Executive", c: "Remote, US", w: "Remote", e: "Contract", p: "$700/day", d: "2026-07-19", dept: "Sales & Marketing", f: "sales" },
  { t: "Content Marketing Manager", c: "Hyderabad, India", w: "On-Site", e: "Contract-to-hire", p: "₹1020/day", d: "2026-07-19", dept: "Sales & Marketing", f: "marketing" },
  { t: "Senior Customer Success Manager", c: "Chicago, IL", w: "Remote", e: "Contract", p: "$53/hr", d: "2026-07-20", dept: "Sales & Marketing", f: "csm" },
  { t: "Market Research Analyst", c: "Wilmington, DE", w: "Hybrid", e: "Contract-to-hire", p: "$47/hr", d: "2026-07-19", dept: "Research", f: "research" },
  { t: "VP of Engineering", c: "Denver, CO", w: "On-Site", e: "Contract", p: "$204/hr", d: "2026-07-19", dept: "Executive", f: "exec" },
  { t: "Staff Machine Learning Engineer", c: "Charlotte, NC", w: "Hybrid", e: "Contract-to-hire", p: "$108/hr", d: "2026-07-17", dept: "Technology", f: "ai" },
  { t: "Staff Data Engineer", c: "Minneapolis, MN", w: "Remote", e: "Contract-to-hire", p: "$74/hr", d: "2026-07-16", dept: "Technology", f: "data" },
  { t: "Full-Stack Developer (React / Node)", c: "Toronto, ON", w: "On-Site", e: "Direct hire", p: "CAD 156K", d: "2026-07-16", dept: "Technology", f: "fullstack" },
  { t: "Senior Backend Engineer (Go)", c: "Calgary, AB", w: "Remote", e: "Direct hire", p: "CAD 213K", d: "2026-07-16", dept: "Technology", f: "backend" },
  { t: "Frontend Engineer (TypeScript)", c: "Dubai, UAE", w: "Hybrid", e: "Direct hire", p: "AED 40K/mo", d: "2026-07-14", dept: "Technology", f: "frontend" },
  { t: "Site Reliability Engineer", c: "Pune, MH", w: "On-Site", e: "Direct hire", p: "$120K", d: "2026-07-16", dept: "Technology", f: "devops" },
  { t: "ML Platform Engineer", c: "Dubai, AE", w: "Hybrid", e: "Contract-to-hire", p: "$560/day", d: "2026-07-13", dept: "Technology", f: "mlops" },
  { t: "Cloud Security Engineer", c: "Pune, India", w: "Remote", e: "Direct hire", p: "₹44 LPA", d: "2026-07-14", dept: "Technology", f: "security" },
  { t: "AWS Solutions Architect", c: "Austin, TX", w: "Hybrid", e: "Contract", p: "$111/hr", d: "2026-07-12", dept: "Technology", f: "cloud" },
  { t: "React Native Engineer", c: "Boston, MA", w: "Hybrid", e: "Direct hire", p: "$160K", d: "2026-07-13", dept: "Technology", f: "mobile" },
  { t: "SDET", c: "Atlanta, GA", w: "Hybrid", e: "Direct hire", p: "$112K", d: "2026-07-12", dept: "Technology", f: "qa" },
  { t: "Technical Product Manager", c: "Phoenix, AZ", w: "Hybrid", e: "Contract-to-hire", p: "$82/hr", d: "2026-07-11", dept: "Product", f: "pm" },
  { t: "UX Researcher", c: "Columbus, OH", w: "Remote", e: "Contract-to-hire", p: "$86/hr", d: "2026-07-10", dept: "Design", f: "design" },
  { t: "Business Analyst", c: "Tampa, FL", w: "On-Site", e: "Contract-to-hire", p: "$59/hr", d: "2026-07-09", dept: "Technology", f: "analytics" },
  { t: "Clinical Project Manager", c: "Cambridge, ON", w: "Remote", e: "Direct hire", p: "CAD 217K", d: "2026-07-11", dept: "Healthcare", f: "clinical" },
  { t: "QA / GMP Manager", c: "Ottawa, ON", w: "On-Site", e: "Contract", p: "CAD $75/hr", d: "2026-07-08", dept: "Healthcare", f: "regulatory" },
  { t: "Director of Nursing", c: "Abu Dhabi, UAE", w: "Hybrid", e: "Contract-to-hire", p: "AED 1700/day", d: "2026-07-10", dept: "Healthcare", f: "nursing" },
  { t: "Privacy Counsel", c: "Columbus, OH", w: "Hybrid", e: "Contract", p: "$370/day", d: "2026-07-09", dept: "Legal", f: "legal" },
  { t: "AML Analyst", c: "Raleigh, NC", w: "Remote", e: "Contract-to-hire", p: "$485/day", d: "2026-07-07", dept: "Finance", f: "compliance" },
  { t: "Finance Manager", c: "Bengaluru, India", w: "Hybrid", e: "Direct hire", p: "₹31 LPA", d: "2026-07-06", dept: "Finance", f: "finance" },
  { t: "Senior FP&A Manager", c: "New York, NY", w: "Hybrid", e: "Direct hire", p: "$173K", d: "2026-07-05", dept: "Finance", f: "fpna" },
  { t: "HR Manager", c: "Seattle, WA", w: "Remote", e: "Direct hire", p: "$97K", d: "2026-07-06", dept: "People", f: "hr" },
  { t: "Talent Acquisition Manager", c: "Dallas, TX", w: "Hybrid", e: "Contract", p: "$45/hr", d: "2026-07-04", dept: "People", f: "ta" },
  { t: "Procurement Manager", c: "San Diego, CA", w: "Remote", e: "Contract-to-hire", p: "$65/hr", d: "2026-07-05", dept: "Operations", f: "supply" },
  { t: "Distribution Center Manager", c: "Nashville, TN", w: "On-Site", e: "Direct hire", p: "$83K", d: "2026-07-03", dept: "Operations", f: "logistics" },
  { t: "Production Supervisor", c: "Remote, US", w: "Remote", e: "Direct hire", p: "$116K", d: "2026-07-05", dept: "Operations", f: "mfg" },
  { t: "Enterprise Account Executive", c: "Vancouver, BC", w: "Remote", e: "Direct hire", p: "CAD 272K", d: "2026-07-04", dept: "Sales & Marketing", f: "sales" },
  { t: "Product Marketing Manager", c: "Remote, Canada", w: "Remote", e: "Contract", p: "CAD $117/hr", d: "2026-07-04", dept: "Sales & Marketing", f: "marketing" },
  { t: "Implementation Consultant", c: "Wilmington, DE", w: "Hybrid", e: "Contract", p: "$430/day", d: "2026-07-02", dept: "Sales & Marketing", f: "csm" },
  { t: "Competitive Intelligence Analyst", c: "Calgary, AB", w: "Hybrid", e: "Direct hire", p: "$65K", d: "2026-07-01", dept: "Research", f: "research" },
  { t: "Chief Financial Officer", c: "Remote, US", w: "Remote", e: "Contract", p: "$815/day", d: "2026-07-02", dept: "Executive", f: "exec" },
  { t: "Applied Scientist — NLP", c: "Hyderabad, India", w: "Hybrid", e: "Direct hire", p: "₹74 LPA", d: "2026-07-01", dept: "Technology", f: "ai" },
  { t: "Analytics Engineer", c: "Chicago, IL", w: "On-Site", e: "Contract-to-hire", p: "$106/hr", d: "2026-07-01", dept: "Technology", f: "data" },
  { t: "Lead Full-Stack Engineer", c: "Wilmington, DE", w: "Hybrid", e: "Direct hire", p: "$131K", d: "2026-06-29", dept: "Technology", f: "fullstack" },
  { t: "Python Backend Engineer", c: "Denver, CO", w: "Remote", e: "Direct hire", p: "$126K", d: "2026-06-28", dept: "Technology", f: "backend" },
  { t: "Lead Frontend Engineer", c: "Charlotte, NC", w: "On-Site", e: "Contract", p: "$61/hr", d: "2026-06-29", dept: "Technology", f: "frontend" },
  { t: "Senior SRE", c: "Minneapolis, MN", w: "On-Site", e: "Contract-to-hire", p: "$104/hr", d: "2026-06-27", dept: "Technology", f: "devops" },
  { t: "MLOps Engineer", c: "Toronto, ON", w: "Hybrid", e: "Contract-to-hire", p: "CAD $126/hr", d: "2026-06-27", dept: "Technology", f: "mlops" },
  { t: "Security Architect", c: "Calgary, AB", w: "On-Site", e: "Contract", p: "CAD $91/hr", d: "2026-06-26", dept: "Technology", f: "security" },
  { t: "Azure Cloud Architect", c: "Dubai, UAE", w: "Remote", e: "Contract", p: "AED 2200/day", d: "2026-06-27", dept: "Technology", f: "cloud" },
  { t: "Mobile Engineering Lead", c: "Pune, MH", w: "Remote", e: "Contract-to-hire", p: "$430/day", d: "2026-06-26", dept: "Technology", f: "mobile" },
  { t: "Test Engineering Lead", c: "Dubai, AE", w: "Remote", e: "Direct hire", p: "$85K", d: "2026-06-26", dept: "Technology", f: "qa" },
  { t: "Group Product Manager", c: "Pune, India", w: "On-Site", e: "Contract", p: "₹1560/day", d: "2026-06-23", dept: "Product", f: "pm" },
  { t: "Design Systems Designer", c: "Austin, TX", w: "On-Site", e: "Direct hire", p: "$177K", d: "2026-06-23", dept: "Design", f: "design" },
  { t: "Marketing Analyst", c: "Boston, MA", w: "On-Site", e: "Contract", p: "$63/hr", d: "2026-06-22", dept: "Technology", f: "analytics" },
  { t: "Clinical Trial Coordinator", c: "Atlanta, GA", w: "On-Site", e: "Contract-to-hire", p: "$70/hr", d: "2026-06-23", dept: "Healthcare", f: "clinical" },
  { t: "Pharmacovigilance Specialist", c: "Phoenix, AZ", w: "Hybrid", e: "Direct hire", p: "$138K", d: "2026-06-22", dept: "Healthcare", f: "regulatory" },
  { t: "Case Manager, RN", c: "Columbus, OH", w: "On-Site", e: "Contract-to-hire", p: "$77/hr", d: "2026-06-22", dept: "Healthcare", f: "nursing" },
  { t: "Contracts Manager", c: "Tampa, FL", w: "Remote", e: "Direct hire", p: "$179K", d: "2026-06-22", dept: "Legal", f: "legal" },
  { t: "Regulatory Compliance Lead", c: "Cambridge, ON", w: "On-Site", e: "Contract", p: "CAD $93/hr", d: "2026-06-20", dept: "Finance", f: "compliance" },
  { t: "Treasury Analyst", c: "Ottawa, ON", w: "Remote", e: "Contract", p: "CAD $97/hr", d: "2026-06-19", dept: "Finance", f: "finance" },
  { t: "Commercial Finance Manager", c: "Abu Dhabi, UAE", w: "On-Site", e: "Contract", p: "AED 1650/day", d: "2026-06-20", dept: "Finance", f: "fpna" },
  { t: "Compensation & Benefits Analyst", c: "Columbus, OH", w: "Remote", e: "Direct hire", p: "$125K", d: "2026-06-20", dept: "People", f: "hr" },
  { t: "Head of Talent Acquisition", c: "Raleigh, NC", w: "Remote", e: "Direct hire", p: "$110K", d: "2026-06-19", dept: "People", f: "ta" },
  { t: "Category Manager", c: "Bengaluru, India", w: "On-Site", e: "Contract-to-hire", p: "₹1715/day", d: "2026-06-18", dept: "Operations", f: "supply" },
  { t: "Transportation Manager", c: "New York, NY", w: "Remote", e: "Direct hire", p: "$119K", d: "2026-06-18", dept: "Operations", f: "logistics" },
  { t: "Plant Manager", c: "Seattle, WA", w: "Remote", e: "Direct hire", p: "$106K", d: "2026-06-18", dept: "Operations", f: "mfg" },
  { t: "Sales Manager", c: "Dallas, TX", w: "On-Site", e: "Contract", p: "$111/hr", d: "2026-06-15", dept: "Sales & Marketing", f: "sales" },
  { t: "Brand Manager", c: "San Diego, CA", w: "Hybrid", e: "Contract", p: "$97/hr", d: "2026-06-15", dept: "Sales & Marketing", f: "marketing" },
  { t: "Technical Account Manager", c: "Nashville, TN", w: "Remote", e: "Contract-to-hire", p: "$73/hr", d: "2026-06-16", dept: "Sales & Marketing", f: "csm" },
  { t: "Talent Researcher", c: "Remote, US", w: "Remote", e: "Contract", p: "$50/hr", d: "2026-06-13", dept: "Research", f: "research" },
  { t: "Chief Operating Officer", c: "Vancouver, BC", w: "On-Site", e: "Contract-to-hire", p: "CAD $273/hr", d: "2026-06-13", dept: "Executive", f: "exec" },
  { t: "Generative AI Engineer", c: "Remote, Canada", w: "Remote", e: "Contract-to-hire", p: "CAD $128/hr", d: "2026-06-12", dept: "Technology", f: "ai" },
  { t: "Senior Analytics Engineer", c: "Wilmington, DE", w: "On-Site", e: "Contract-to-hire", p: "$495/day", d: "2026-06-12", dept: "Technology", f: "data" },
  { t: "Full-Stack Engineer", c: "Calgary, AB", w: "Remote", e: "Contract-to-hire", p: "$495/day", d: "2026-06-12", dept: "Technology", f: "fullstack" },
  { t: ".NET Backend Engineer", c: "Remote, US", w: "Remote", e: "Contract", p: "$485/day", d: "2026-06-13", dept: "Technology", f: "backend" },
  { t: "Frontend Engineer", c: "Hyderabad, India", w: "Hybrid", e: "Direct hire", p: "₹42 LPA", d: "2026-06-12", dept: "Technology", f: "frontend" },
  { t: "Platform Engineer", c: "Chicago, IL", w: "Hybrid", e: "Contract-to-hire", p: "$108/hr", d: "2026-06-10", dept: "Technology", f: "devops" },
  { t: "Senior MLOps Engineer", c: "Wilmington, DE", w: "Hybrid", e: "Contract", p: "$88/hr", d: "2026-06-10", dept: "Technology", f: "mlops" },
  { t: "GRC Analyst", c: "Denver, CO", w: "Remote", e: "Direct hire", p: "$148K", d: "2026-06-10", dept: "Technology", f: "security" },
  { t: "GCP Data Architect", c: "Charlotte, NC", w: "Hybrid", e: "Contract-to-hire", p: "$91/hr", d: "2026-06-08", dept: "Technology", f: "cloud" },
  { t: "iOS Engineer", c: "Minneapolis, MN", w: "On-Site", e: "Contract", p: "$93/hr", d: "2026-06-08", dept: "Technology", f: "mobile" },
  { t: "QA Automation Engineer", c: "Toronto, ON", w: "Hybrid", e: "Direct hire", p: "CAD 161K", d: "2026-06-08", dept: "Technology", f: "qa" },
  { t: "Product Owner", c: "Calgary, AB", w: "Remote", e: "Contract-to-hire", p: "CAD $118/hr", d: "2026-06-08", dept: "Product", f: "pm" },
  { t: "UX Writer", c: "Dubai, UAE", w: "On-Site", e: "Direct hire", p: "AED 45K/mo", d: "2026-06-07", dept: "Design", f: "design" },
  { t: "Financial Data Analyst", c: "Pune, MH", w: "Remote", e: "Contract", p: "$305/day", d: "2026-06-05", dept: "Technology", f: "analytics" },
  { t: "Biostatistician", c: "Dubai, AE", w: "Remote", e: "Contract", p: "$355/day", d: "2026-06-05", dept: "Healthcare", f: "clinical" },
  { t: "Validation Engineer", c: "Pune, India", w: "Remote", e: "Contract-to-hire", p: "₹1460/day", d: "2026-06-04", dept: "Healthcare", f: "regulatory" },
  { t: "Nurse Manager", c: "Austin, TX", w: "Remote", e: "Contract-to-hire", p: "$71/hr", d: "2026-06-05", dept: "Healthcare", f: "nursing" },
  { t: "Paralegal Lead", c: "Boston, MA", w: "Hybrid", e: "Contract-to-hire", p: "$106/hr", d: "2026-06-03", dept: "Legal", f: "legal" },
  { t: "Internal Auditor", c: "Atlanta, GA", w: "On-Site", e: "Direct hire", p: "$138K", d: "2026-06-02", dept: "Finance", f: "compliance" },
  { t: "Revenue Accountant", c: "Phoenix, AZ", w: "Hybrid", e: "Contract-to-hire", p: "$89/hr", d: "2026-06-02", dept: "Finance", f: "finance" },
  { t: "FP&A Analyst", c: "Columbus, OH", w: "Remote", e: "Contract", p: "$61/hr", d: "2026-06-01", dept: "Finance", f: "fpna" },
  { t: "L&D Manager", c: "Tampa, FL", w: "Remote", e: "Contract", p: "$60/hr", d: "2026-06-02", dept: "People", f: "hr" },
  { t: "Talent Sourcer", c: "Cambridge, ON", w: "Hybrid", e: "Contract", p: "CAD $59/hr", d: "2026-06-01", dept: "People", f: "ta" },
  { t: "Demand Planner", c: "Ottawa, ON", w: "Remote", e: "Contract-to-hire", p: "CAD $76/hr", d: "2026-06-02", dept: "Operations", f: "supply" },
  { t: "Logistics Coordinator", c: "Abu Dhabi, UAE", w: "On-Site", e: "Contract", p: "AED 1100/day", d: "2026-05-31", dept: "Operations", f: "logistics" },
  { t: "Quality Engineer", c: "Columbus, OH", w: "Remote", e: "Contract", p: "$370/day", d: "2026-05-31", dept: "Operations", f: "mfg" },
  { t: "VP of Sales", c: "Raleigh, NC", w: "On-Site", e: "Direct hire", p: "$190K", d: "2026-05-29", dept: "Sales & Marketing", f: "sales" },
  { t: "Marketing Director", c: "Bengaluru, India", w: "Hybrid", e: "Contract", p: "₹1075/day", d: "2026-05-30", dept: "Sales & Marketing", f: "marketing" },
  { t: "Customer Success Manager", c: "New York, NY", w: "On-Site", e: "Contract", p: "$66/hr", d: "2026-05-28", dept: "Sales & Marketing", f: "csm" },
  { t: "Market Research Analyst", c: "Seattle, WA", w: "Hybrid", e: "Contract", p: "$59/hr", d: "2026-05-27", dept: "Research", f: "research" },
  { t: "VP of Product", c: "Dallas, TX", w: "Hybrid", e: "Direct hire", p: "$329K", d: "2026-05-28", dept: "Executive", f: "exec" },
  { t: "Computer Vision Engineer", c: "San Diego, CA", w: "Remote", e: "Contract", p: "$129/hr", d: "2026-05-27", dept: "Technology", f: "ai" },
  { t: "Data Architect", c: "Nashville, TN", w: "Hybrid", e: "Contract-to-hire", p: "$75/hr", d: "2026-05-26", dept: "Technology", f: "data" },
  { t: "Senior Full-Stack Engineer", c: "Remote, US", w: "Remote", e: "Contract-to-hire", p: "$72/hr", d: "2026-05-25", dept: "Technology", f: "fullstack" },
  { t: "Staff Backend Engineer", c: "Vancouver, BC", w: "On-Site", e: "Contract", p: "CAD $96/hr", d: "2026-05-26", dept: "Technology", f: "backend" },
  { t: "Senior Frontend Engineer (React)", c: "Remote, Canada", w: "Remote", e: "Contract", p: "CAD $86/hr", d: "2026-05-24", dept: "Technology", f: "frontend" },
  { t: "Infrastructure Engineer", c: "Wilmington, DE", w: "Remote", e: "Contract", p: "$420/day", d: "2026-05-25", dept: "Technology", f: "devops" },
  { t: "ML Platform Engineer", c: "Calgary, AB", w: "Hybrid", e: "Contract", p: "$535/day", d: "2026-05-23", dept: "Technology", f: "mlops" },
  { t: "Security Engineer", c: "Remote, US", w: "Remote", e: "Contract-to-hire", p: "$535/day", d: "2026-05-22", dept: "Technology", f: "security" },
  { t: "Cloud Engineer", c: "Hyderabad, India", w: "Remote", e: "Contract-to-hire", p: "₹1360/day", d: "2026-05-23", dept: "Technology", f: "cloud" },
  { t: "Senior Android Engineer", c: "Chicago, IL", w: "On-Site", e: "Contract-to-hire", p: "$81/hr", d: "2026-05-22", dept: "Technology", f: "mobile" },
  { t: "Senior QA Engineer", c: "Wilmington, DE", w: "On-Site", e: "Direct hire", p: "$157K", d: "2026-05-21", dept: "Technology", f: "qa" },
  { t: "Product Manager", c: "Denver, CO", w: "On-Site", e: "Contract", p: "$76/hr", d: "2026-05-21", dept: "Product", f: "pm" },
  { t: "Product Designer", c: "Charlotte, NC", w: "On-Site", e: "Direct hire", p: "$116K", d: "2026-05-21", dept: "Design", f: "design" },
  { t: "Data Analyst", c: "Minneapolis, MN", w: "Hybrid", e: "Direct hire", p: "$143K", d: "2026-05-19", dept: "Technology", f: "analytics" },
  { t: "Clinical Data Manager", c: "Toronto, ON", w: "Hybrid", e: "Contract", p: "CAD $97/hr", d: "2026-05-21", dept: "Healthcare", f: "clinical" },
  { t: "Regulatory Affairs Manager", c: "Calgary, AB", w: "Hybrid", e: "Contract", p: "CAD $64/hr", d: "2026-05-18", dept: "Healthcare", f: "regulatory" },
  { t: "Clinical Nurse Specialist", c: "Dubai, UAE", w: "On-Site", e: "Contract", p: "AED 1250/day", d: "2026-05-17", dept: "Healthcare", f: "nursing" },
  { t: "General Counsel", c: "Pune, MH", w: "Remote", e: "Contract", p: "$455/day", d: "2026-05-18", dept: "Legal", f: "legal" },
  { t: "Compliance Officer", c: "Dubai, AE", w: "Hybrid", e: "Direct hire", p: "$85K", d: "2026-05-16", dept: "Finance", f: "compliance" },
  { t: "Financial Controller", c: "Pune, India", w: "On-Site", e: "Direct hire", p: "₹54 LPA", d: "2026-05-17", dept: "Finance", f: "finance" },
  { t: "FP&A Manager", c: "Austin, TX", w: "Hybrid", e: "Contract", p: "$73/hr", d: "2026-05-16", dept: "Finance", f: "fpna" },
  { t: "HR Business Partner", c: "Boston, MA", w: "Hybrid", e: "Direct hire", p: "$159K", d: "2026-05-15", dept: "People", f: "hr" },
  { t: "Technical Recruiter", c: "Atlanta, GA", w: "Hybrid", e: "Contract", p: "$97/hr", d: "2026-05-16", dept: "People", f: "ta" },
  { t: "Supply Chain Director", c: "Phoenix, AZ", w: "Hybrid", e: "Contract", p: "$79/hr", d: "2026-05-16", dept: "Operations", f: "supply" },
  { t: "Logistics Manager", c: "Columbus, OH", w: "Remote", e: "Contract-to-hire", p: "$63/hr", d: "2026-05-14", dept: "Operations", f: "logistics" },
  { t: "Maintenance Manager", c: "Tampa, FL", w: "Hybrid", e: "Contract-to-hire", p: "$53/hr", d: "2026-05-12", dept: "Operations", f: "mfg" },
  { t: "Sales Engineer", c: "Cambridge, ON", w: "Remote", e: "Contract-to-hire", p: "CAD $156/hr", d: "2026-05-14", dept: "Sales & Marketing", f: "sales" },
  { t: "SEO Manager", c: "Ottawa, ON", w: "Remote", e: "Direct hire", p: "CAD 148K", d: "2026-05-12", dept: "Sales & Marketing", f: "marketing" },
  { t: "Senior Customer Success Manager", c: "Abu Dhabi, UAE", w: "Hybrid", e: "Contract", p: "AED 1300/day", d: "2026-05-13", dept: "Sales & Marketing", f: "csm" },
  { t: "Competitive Intelligence Analyst", c: "Columbus, OH", w: "Hybrid", e: "Direct hire", p: "$100K", d: "2026-05-12", dept: "Research", f: "research" },
  { t: "Head of Data", c: "Raleigh, NC", w: "Hybrid", e: "Direct hire", p: "$365K", d: "2026-05-10", dept: "Executive", f: "exec" },
  { t: "AI Platform Engineer", c: "Bengaluru, India", w: "Hybrid", e: "Contract-to-hire", p: "₹1800/day", d: "2026-05-10", dept: "Technology", f: "ai" },
  { t: "BI Developer", c: "New York, NY", w: "On-Site", e: "Contract-to-hire", p: "$68/hr", d: "2026-05-09", dept: "Technology", f: "data" },
  { t: "Full-Stack Developer (React / Node)", c: "Seattle, WA", w: "Remote", e: "Contract", p: "$90/hr", d: "2026-05-09", dept: "Technology", f: "fullstack" },
  { t: "Backend Engineer", c: "Dallas, TX", w: "Hybrid", e: "Contract-to-hire", p: "$85/hr", d: "2026-05-10", dept: "Technology", f: "backend" },
  { t: "Frontend Engineer (TypeScript)", c: "San Diego, CA", w: "Remote", e: "Direct hire", p: "$142K", d: "2026-05-07", dept: "Technology", f: "frontend" },
  { t: "DevOps Engineer", c: "Nashville, TN", w: "Remote", e: "Direct hire", p: "$194K", d: "2026-05-08", dept: "Technology", f: "devops" },
  { t: "MLOps Engineer", c: "Remote, US", w: "Remote", e: "Contract-to-hire", p: "$105/hr", d: "2026-05-08", dept: "Technology", f: "mlops" },
  { t: "Senior Security Engineer — AppSec", c: "Vancouver, BC", w: "Hybrid", e: "Contract-to-hire", p: "CAD $83/hr", d: "2026-05-07", dept: "Technology", f: "security" },
  { t: "Solutions Architect — Cloud", c: "Remote, Canada", w: "Remote", e: "Contract-to-hire", p: "CAD $125/hr", d: "2026-05-06", dept: "Technology", f: "cloud" },
  { t: "React Native Engineer", c: "Wilmington, DE", w: "Hybrid", e: "Contract", p: "$445/day", d: "2026-05-05", dept: "Technology", f: "mobile" },
  { t: "SDET", c: "Calgary, AB", w: "Hybrid", e: "Direct hire", p: "$85K", d: "2026-05-04", dept: "Technology", f: "qa" },
  { t: "Senior Product Manager", c: "Remote, US", w: "Remote", e: "Contract", p: "$560/day", d: "2026-05-05", dept: "Product", f: "pm" },
  { t: "Senior Product Designer", c: "Hyderabad, India", w: "Remote", e: "Direct hire", p: "₹52 LPA", d: "2026-05-04", dept: "Design", f: "design" },
  { t: "Senior Data Analyst", c: "Chicago, IL", w: "Remote", e: "Direct hire", p: "$118K", d: "2026-05-03", dept: "Technology", f: "analytics" },
  { t: "Clinical Research Associate", c: "Wilmington, DE", w: "Hybrid", e: "Contract", p: "$50/hr", d: "2026-05-02", dept: "Healthcare", f: "clinical" },
  { t: "Regulatory Affairs Specialist", c: "Denver, CO", w: "On-Site", e: "Contract", p: "$64/hr", d: "2026-05-01", dept: "Healthcare", f: "regulatory" },
  { t: "Director of Nursing", c: "Charlotte, NC", w: "Hybrid", e: "Direct hire", p: "$143K", d: "2026-05-01", dept: "Healthcare", f: "nursing" },
  { t: "Corporate Counsel", c: "Minneapolis, MN", w: "Remote", e: "Contract", p: "$89/hr", d: "2026-05-01", dept: "Legal", f: "legal" },
  { t: "Compliance Manager", c: "Toronto, ON", w: "On-Site", e: "Contract-to-hire", p: "CAD $62/hr", d: "2026-04-29", dept: "Finance", f: "compliance" },
  { t: "Assistant Controller", c: "Calgary, AB", w: "Hybrid", e: "Contract", p: "CAD $101/hr", d: "2026-04-29", dept: "Finance", f: "finance" },
  { t: "Senior FP&A Manager", c: "Dubai, UAE", w: "Hybrid", e: "Contract-to-hire", p: "AED 1550/day", d: "2026-04-29", dept: "Finance", f: "fpna" },
  { t: "Senior HR Business Partner", c: "Pune, MH", w: "On-Site", e: "Direct hire", p: "$120K", d: "2026-04-30", dept: "People", f: "hr" },
  { t: "Senior Technical Recruiter", c: "Dubai, AE", w: "Hybrid", e: "Direct hire", p: "$110K", d: "2026-04-27", dept: "People", f: "ta" },
  { t: "Supply Chain Analyst", c: "Pune, India", w: "Remote", e: "Direct hire", p: "₹49 LPA", d: "2026-04-27", dept: "Operations", f: "supply" },
  { t: "Distribution Center Manager", c: "Austin, TX", w: "Remote", e: "Contract", p: "$51/hr", d: "2026-04-26", dept: "Operations", f: "logistics" },
  { t: "Manufacturing Engineer", c: "Boston, MA", w: "Remote", e: "Contract-to-hire", p: "$89/hr", d: "2026-04-25", dept: "Operations", f: "mfg" },
  { t: "Account Executive", c: "Atlanta, GA", w: "On-Site", e: "Direct hire", p: "$145K", d: "2026-04-26", dept: "Sales & Marketing", f: "sales" },
  { t: "Demand Generation Manager", c: "Phoenix, AZ", w: "On-Site", e: "Contract", p: "$73/hr", d: "2026-04-24", dept: "Sales & Marketing", f: "marketing" },
  { t: "Implementation Consultant", c: "Columbus, OH", w: "On-Site", e: "Contract", p: "$48/hr", d: "2026-04-26", dept: "Sales & Marketing", f: "csm" },
  { t: "Talent Researcher", c: "Tampa, FL", w: "Remote", e: "Contract", p: "$48/hr", d: "2026-04-24", dept: "Research", f: "research" },
  { t: "Chief Technology Officer", c: "Cambridge, ON", w: "On-Site", e: "Direct hire", p: "CAD 504K", d: "2026-04-25", dept: "Executive", f: "exec" },
  { t: "Lead AI Engineer", c: "Ottawa, ON", w: "On-Site", e: "Contract-to-hire", p: "CAD $161/hr", d: "2026-04-22", dept: "Technology", f: "ai" },
  { t: "Data Platform Engineer", c: "Abu Dhabi, UAE", w: "On-Site", e: "Contract", p: "AED 1350/day", d: "2026-04-22", dept: "Technology", f: "data" },
  { t: "Lead Full-Stack Engineer", c: "Columbus, OH", w: "On-Site", e: "Direct hire", p: "$125K", d: "2026-04-21", dept: "Technology", f: "fullstack" },
  { t: "Senior Backend Engineer (Java)", c: "Raleigh, NC", w: "Remote", e: "Contract", p: "$355/day", d: "2026-04-22", dept: "Technology", f: "backend" },
  { t: "Lead Frontend Engineer", c: "Bengaluru, India", w: "On-Site", e: "Contract-to-hire", p: "₹1260/day", d: "2026-04-20", dept: "Technology", f: "frontend" },
  { t: "Senior DevOps Engineer", c: "New York, NY", w: "Remote", e: "Contract", p: "$106/hr", d: "2026-04-21", dept: "Technology", f: "devops" },
  { t: "Senior MLOps Engineer", c: "Seattle, WA", w: "Remote", e: "Direct hire", p: "$212K", d: "2026-04-19", dept: "Technology", f: "mlops" },
  { t: "Cloud Security Engineer", c: "Dallas, TX", w: "On-Site", e: "Contract", p: "$68/hr", d: "2026-04-19", dept: "Technology", f: "security" },
  { t: "AWS Solutions Architect", c: "San Diego, CA", w: "On-Site", e: "Contract-to-hire", p: "$108/hr", d: "2026-04-18", dept: "Technology", f: "cloud" },
  { t: "Mobile Engineering Lead", c: "Nashville, TN", w: "Remote", e: "Contract-to-hire", p: "$88/hr", d: "2026-04-19", dept: "Technology", f: "mobile" },
  { t: "Test Engineering Lead", c: "Remote, US", w: "Remote", e: "Direct hire", p: "$152K", d: "2026-04-18", dept: "Technology", f: "qa" },
  { t: "Technical Product Manager", c: "Vancouver, BC", w: "Remote", e: "Contract", p: "CAD $99/hr", d: "2026-04-18", dept: "Product", f: "pm" },
  { t: "UX Researcher", c: "Remote, Canada", w: "Remote", e: "Contract", p: "CAD $75/hr", d: "2026-04-16", dept: "Design", f: "design" },
  { t: "Business Analyst", c: "Wilmington, DE", w: "On-Site", e: "Direct hire", p: "$100K", d: "2026-04-17", dept: "Technology", f: "analytics" },
  { t: "Clinical Project Manager", c: "Calgary, AB", w: "Hybrid", e: "Direct hire", p: "$135K", d: "2026-04-16", dept: "Healthcare", f: "clinical" },
  { t: "QA / GMP Manager", c: "Remote, US", w: "Remote", e: "Contract", p: "$355/day", d: "2026-04-14", dept: "Healthcare", f: "regulatory" },
  { t: "Case Manager, RN", c: "Hyderabad, India", w: "On-Site", e: "Direct hire", p: "₹41 LPA", d: "2026-04-14", dept: "Healthcare", f: "nursing" },
  { t: "Senior Commercial Counsel", c: "Chicago, IL", w: "On-Site", e: "Direct hire", p: "$261K", d: "2026-04-14", dept: "Legal", f: "legal" },
  { t: "AML Analyst", c: "Wilmington, DE", w: "Remote", e: "Direct hire", p: "$115K", d: "2026-04-13", dept: "Finance", f: "compliance" },
  { t: "Finance Manager", c: "Denver, CO", w: "Hybrid", e: "Contract-to-hire", p: "$91/hr", d: "2026-04-13", dept: "Finance", f: "finance" },
  { t: "Commercial Finance Manager", c: "Charlotte, NC", w: "Hybrid", e: "Contract", p: "$71/hr", d: "2026-04-13", dept: "Finance", f: "fpna" },
  { t: "HR Manager", c: "Minneapolis, MN", w: "Hybrid", e: "Contract-to-hire", p: "$50/hr", d: "2026-04-13", dept: "People", f: "hr" },
  { t: "Talent Acquisition Manager", c: "Toronto, ON", w: "Remote", e: "Contract-to-hire", p: "CAD $73/hr", d: "2026-04-11", dept: "People", f: "ta" },
];

export type FamText = { s: string; r: string[]; q: string[] };

export const FAMTXT: Record<string, FamText> = {
  "ai": { s: "A client building production LLM and machine-learning capability needs a %T% who has shipped models into real traffic, not just notebooks.", r: ["Design and ship retrieval, training or inference pipelines that carry live traffic.", "Own an accuracy, latency or cost metric the business actually watches.", "Build the evaluation harness so regressions surface before release, not after.", "Partner with product on guardrails for customer-facing AI features."], q: ["Substantial Python and at least one production ML or LLM system behind you.", "Comfortable with vector stores, orchestration frameworks and hosted model APIs.", "Able to reason about cost and latency as first-class constraints."] },
  "data": { s: "A client consolidating fragmented pipelines onto a modern warehouse is hiring a %T% to own the architecture rather than inherit it.", r: ["Model and land the warehouse layers, contracts and SLAs.", "Migrate legacy jobs onto tested, documented transformations.", "Put data quality gates in front of anything the business reports on.", "Set the standard for review, testing and deployment on the data team."], q: ["Expert SQL plus Python; production dbt and a cloud warehouse.", "Real ownership of a migration or a greenfield build, end to end.", "Can defend an architecture decision to non-technical stakeholders."] },
  "fullstack": { s: "A product team shipping weekly needs a %T% who can carry a feature from design conversation to production.", r: ["Build features end to end across the front end and the services behind them.", "Work directly with design on interaction detail — this team cares about craft.", "Write the tests; there is no separate QA function.", "Share on-call for the services you own."], q: ["Production React and Node/TypeScript at a senior standard.", "Effective in a codebase you did not write.", "Bias toward shipping without breaking things."] },
  "backend": { s: "A client under real transaction load is hiring a %T% to strengthen the services at the centre of the business.", r: ["Design and ship services that hold up under production load.", "Extract bounded contexts from legacy code without customer-visible disruption.", "Raise the testing bar around the critical paths.", "Document the seams so the team can follow the pattern."], q: ["Deep experience in the language and framework named in the title.", "Track record with performance, correctness or migration work at scale.", "Domain where mistakes are expensive — payments, ledgers, health or similar."] },
  "frontend": { s: "A design-led product company needs a %T% to rebuild an interface people use all day.", r: ["Build the core application UI to a high craft standard.", "Hold the line on accessibility and performance budgets.", "Collaborate closely with design on motion and interaction.", "Contribute to a shared component library."], q: ["Deep React and TypeScript in production.", "Real accessibility knowledge — WCAG in practice, not in theory.", "A portfolio of interfaces you will defend."] },
  "devops": { s: "A client scaling its platform needs a %T% to make deployment and reliability boring in the best sense.", r: ["Own infrastructure as code and the paved road other teams deploy on.", "Define SLOs with product owners and make them stick.", "Lead incident review and drive the follow-through, not just the writeup.", "Reduce alert noise so on-call is sustainable."], q: ["Kubernetes, Terraform and one major cloud to a production standard.", "Genuine incident command experience.", "Able to influence engineering teams you do not manage."] },
  "mlops": { s: "A client moving models from experiment to production is hiring a %T% to build the platform every model team will use.", r: ["Build the training-to-serving path: features, registry, deployment, monitoring.", "Take model deployment from weeks to days without loosening governance.", "Make lineage and approvals auditable for risk and compliance.", "Own the platform's reliability targets."], q: ["Platform or infrastructure engineering with ML systems experience.", "Kubernetes, Terraform and a major cloud in anger.", "Patience for a regulated environment."] },
  "security": { s: "A client under enterprise and regulatory scrutiny needs a %T% who can raise the bar without stopping delivery.", r: ["Run threat modelling and secure design review on new work.", "Own security tooling and, more importantly, triage developers trust.", "Lead remediation with engineering rather than filing tickets at them.", "Support customer security reviews and audit cycles."], q: ["Application, cloud or GRC security depth matching the title.", "Able to read and write code, not only scan it.", "Has shepherded a compliance audit to completion."] },
  "cloud": { s: "A client modernising its estate needs a %T% who has designed for cost, resilience and the real organisation.", r: ["Own architecture for platform or customer-facing workloads.", "Run proofs of concept that reflect the deployment, not a demo.", "Bring cloud spend under control with named owners and budgets.", "Support delivery teams through implementation."], q: ["Deep experience in the named cloud, plus one other.", "Credible with engineers and with procurement.", "Migration or modernisation work you can walk through."] },
  "mobile": { s: "A client with a consumer-scale app needs a %T% to own quality on the platform users actually judge them by.", r: ["Ship features and own crash-free rate and start-up performance.", "Work with design on platform-native interaction detail.", "Improve release confidence with automated testing and staged rollout.", "Mentor engineers newer to mobile."], q: ["Production experience on the platform named in the title.", "Store release process end to end.", "Performance profiling as a habit, not an event."] },
  "qa": { s: "A client with a growing product surface needs a %T% to build automation the team relies on.", r: ["Build and maintain automated coverage across the critical journeys.", "Wire tests into CI so failures block, and are trusted.", "Work with engineers on testability rather than testing after the fact.", "Own release-readiness reporting."], q: ["Strong automation skills in a mainstream framework.", "API and UI coverage design experience.", "Comfortable pushing back on untestable design."] },
  "pm": { s: "A client needs a %T% to own a real problem area with a team, a metric and no hand-holding.", r: ["Own the roadmap for your area and the metric it moves.", "Do the discovery work — talk to users, not just stakeholders.", "Write clearly; this team makes decisions in documents.", "Make build-versus-buy calls with engineering."], q: ["Shipped products with measurable outcomes you can describe.", "Comfortable with technical depth in the relevant domain.", "Strong written communication."] },
  "design": { s: "A client rebuilding a core experience needs a %T% comfortable with dense, real-world complexity.", r: ["Own end-to-end design for a significant part of the product.", "Run research that changes decisions rather than decorating them.", "Build and maintain components alongside front-end engineers.", "Present direction to leadership and defend the trade-offs."], q: ["Portfolio showing complex or enterprise product work.", "Fluent in Figma with a systems mindset.", "Able to work in the open with engineers."] },
  "analytics": { s: "A client needs a %T% who can turn messy operational data into decisions people act on.", r: ["Own reporting and analysis for a business area end to end.", "Build models and dashboards stakeholders trust and use.", "Investigate the questions behind the question.", "Improve data quality where you find it lacking."], q: ["Advanced SQL plus a BI tool; Python or R an advantage.", "Track record of analysis that changed a decision.", "Clear communication with non-analysts."] },
  "clinical": { s: "A clinical-stage client running concurrent studies needs a %T% who keeps timelines honest and data clean.", r: ["Own your remit across active studies through to database lock.", "Drive query resolution with sites and CROs.", "Prepare clean deliverables for interim and final analysis.", "Keep documentation inspection-ready throughout."], q: ["Clinical experience in pharma, biotech or CRO.", "Hands-on with a major EDC platform.", "Working knowledge of GCP and CDISC standards."] },
  "regulatory": { s: "A regulated manufacturer needs a %T% to own submissions and quality without becoming a bottleneck.", r: ["Own technical documentation and regulatory submissions in scope.", "Act as primary contact for the notified body or agency.", "Advise R&D early so design decisions do not create regulatory debt.", "Maintain post-market surveillance and vigilance obligations."], q: ["Regulatory or quality experience in devices, pharma or biotech.", "Direct submission experience in the relevant jurisdiction.", "Comfortable holding a line with commercial pressure present."] },
  "nursing": { s: "A provider client needs a %T% to lead clinically while carrying real operational accountability.", r: ["Lead a clinical team across shifts, including hiring and development.", "Own quality, safety and patient-experience measures for your unit.", "Partner with physicians and operations on capacity and flow.", "Keep the unit survey-ready."], q: ["Active RN licence in the relevant jurisdiction.", "Prior charge, supervisory or leadership experience.", "Credible clinically with the team you lead."] },
  "legal": { s: "A client scaling across jurisdictions needs a %T% who can close deals and reduce risk at the same time.", r: ["Own the contract lifecycle in your scope and negotiate to close.", "Build playbooks and templates so the business can self-serve standard cases.", "Advise commercial teams commercially, not just legally.", "Support privacy, vendor and regulatory matters alongside the GC."], q: ["Relevant in-house or top-tier firm experience.", "High-volume contracting with sophisticated counterparties.", "Licensed and in good standing in a relevant jurisdiction."] },
  "compliance": { s: "A financial services client is strengthening its second line and needs a %T% who has been through an examination.", r: ["Own the monitoring programme and its testing calendar.", "Manage regulatory examinations and remediation tracking.", "Deliver training people retain.", "Advise on new product and market entry."], q: ["Compliance or audit experience in financial services.", "Direct experience of a regulatory examination.", "Relevant certification preferred."] },
  "finance": { s: "A client with growing complexity needs a %T% to bring rigour to close, controls and reporting.", r: ["Own the close and statutory reporting in your scope.", "Strengthen controls without slowing the business.", "Manage the audit relationship end to end.", "Improve close-to-report speed without sacrificing accuracy."], q: ["Qualified accountant or equivalent experience.", "Multi-entity or multi-currency exposure.", "Comfortable rebuilding rather than maintaining."] },
  "fpna": { s: "A client under investor or lender scrutiny needs a %T% to rebuild forecasting people believe.", r: ["Own the model and the forecast cycle.", "Build the reporting pack leadership actually reads.", "Partner with operators on cost and margin analysis.", "Bring discipline to variance explanation."], q: ["Advanced modelling; able to rebuild from first principles.", "Experience presenting to a board, PE sponsor or lender group.", "Business partnering instinct, not just reporting."] },
  "hr": { s: "A client scaling its people function needs a %T% who can advise leaders and still do the work.", r: ["Partner with leaders on organisation, performance and retention.", "Handle employee relations matters with judgement and care.", "Improve a people process that is currently manual or unclear.", "Use data to make the case, not just the feeling."], q: ["Generalist or specialist depth matching the title.", "Comfortable challenging senior stakeholders.", "Multi-site or multi-country exposure an advantage."] },
  "ta": { s: "A client hiring at pace needs a %T% who can fill roles without lowering the bar.", r: ["Own requisitions end to end, from intake to offer.", "Source actively — this is not an inbound role.", "Improve process, scorecards and interviewer capability.", "Report honestly on time-to-hire and pipeline health."], q: ["Recruitment experience in the relevant market and function.", "Strong direct sourcing capability.", "Able to hold hiring managers to a standard."] },
  "supply": { s: "A client under cost and service pressure needs a %T% to bring control to planning and sourcing.", r: ["Own planning, sourcing or category responsibility in scope.", "Renegotiate supplier agreements and hold the savings.", "Bring inventory accuracy and service levels to target.", "Build the S&OP cadence the business lacks."], q: ["Supply chain or procurement experience at the relevant level.", "Demonstrated cost reduction without service degradation.", "ERP fluency and strong analytics."] },
  "logistics": { s: "A client moving real volume needs a %T% who can keep service levels while cost comes down.", r: ["Own day-to-day logistics or distribution performance.", "Manage carrier and 3PL relationships on cost and service.", "Improve throughput and accuracy with the team you have.", "Own safety and compliance in your operation."], q: ["Logistics or distribution experience at the relevant scale.", "Comfortable on the floor and in the numbers.", "WMS or TMS experience."] },
  "mfg": { s: "A manufacturing client needs a %T% to hold safety, quality and output while improving the process.", r: ["Own safety, quality, output and cost in your area.", "Lead continuous improvement with measurable results.", "Develop supervisors and technicians beneath you.", "Partner with engineering on process and equipment change."], q: ["Manufacturing experience at the relevant level.", "Lean or Six Sigma in practice, not just certification.", "Unionised environment experience where applicable."] },
  "sales": { s: "A client with a proven product needs a %T% who can build pipeline and close it.", r: ["Own a number and the pipeline that supports it.", "Sell into the relevant buyer with a real point of view.", "Work the whole cycle, including procurement and legal.", "Forecast honestly."], q: ["Quota-carrying experience with evidence of attainment.", "Relevant market, deal size and sales cycle.", "Comfortable prospecting, not just closing warm leads."] },
  "marketing": { s: "A client that needs pipeline, not impressions, is hiring a %T% to own a measurable channel.", r: ["Own your channel or programme and the pipeline it generates.", "Build the reporting that ties spend to revenue.", "Work closely with sales on definitions and handoff.", "Raise the quality bar on what goes out."], q: ["Depth in the discipline named in the title.", "Comfortable with attribution and its limits.", "Strong writing and editorial judgement."] },
  "csm": { s: "A client protecting its base needs a %T% who can drive adoption and renew without discounting.", r: ["Own retention and expansion for a book of accounts.", "Drive adoption with a real onboarding and success plan.", "Be the customer's advocate internally, with evidence.", "Forecast renewal risk early."], q: ["Customer success or account management at the relevant segment.", "Technical enough to be credible with practitioner users.", "Track record on retention or expansion."] },
  "research": { s: "A client team needs a %T% to map markets and produce intelligence people act on.", r: ["Build market maps, target lists and competitive briefs.", "Run first-touch outreach and qualify interest.", "Keep pipeline and research data accurate.", "Brief stakeholders on market reality, including when unwelcome."], q: ["Research, sourcing or analyst experience.", "Strong Boolean and desk-research capability.", "Excellent written English."] },
  "exec": { s: "A client at an inflection point is hiring a %T% — a confidential, retained search led by a Rivago partner.", r: ["Own the function end to end, through your leadership team.", "Set strategy and be accountable for delivering it.", "Build and level the team, fairly and quickly.", "Represent the function to the board and to investors."], q: ["Senior leadership experience at or near this level.", "Has scaled an organisation through a comparable transition.", "Still close enough to the work to earn respect."] },
};

export const EEO = "Rivago Infotech is an equal opportunity partner. Our clients consider all qualified applicants without regard to race, religion, sex, age, marital status, national origin, sexual orientation, citizenship status, disability or any other protected characteristic. If you need an accommodation at any point in the process, tell your Rivago partner and we will arrange it.";
