export const routes = {
  home: "/",
  hireTalent: "/hire-talent",
  services: "/services",
  directHire: "/services/direct-hire",
  contractStaffing: "/services/contract-staffing",
  temporaryStaffing: "/services/temporary-staffing",
  rpo: "/services/rpo",
  executiveSearch: "/services/executive-search",
  interimLeadership: "/services/interim-leadership",
  employerOfRecord: "/services/employer-of-record",
  industries: "/industries",
  resources: "/resources",
  article: "/resources/article",
  caseStudy: "/resources/case-study",
  about: "/about",
  contactUs: "/contact-us",
  career: "/career",
  viewJobs: "/view-jobs",
  role: "/view-jobs/role",
  searchJobs: "/search-jobs",
  openPositions: "/open-positions",
  signIn: "/sign-in",
  privacy: "/privacy",
  terms: "/terms",
  cookies: "/cookies",
} as const;

export const servicesList = [
  { n: "01", title: "Staffing Solutions", desc: "Start here — the full overview of how Rivago engages, and which structure fits the role you are filling.", meta: "Overview", href: routes.services },
  { n: "02", title: "Direct hire", desc: "Permanent placements across every function and level, on a contingent fee you pay only on a hire that sticks.", meta: "48-hour shortlist", href: routes.directHire },
  { n: "03", title: "Contract staffing", desc: "Skilled professionals on fixed-term engagements. We run payroll, compliance and worker classification.", meta: "Talent in 5–7 days", href: routes.contractStaffing, tag: "Popular" },
  { n: "04", title: "Temporary staffing", desc: "On-demand cover for peaks, seasonal spikes and leave. Deployed in days, scaled up or down as work changes.", meta: "Boots on site fast", href: routes.temporaryStaffing },
  { n: "05", title: "Executive search", desc: "Confidential retained search for VP- to C-suite roles, with weekly written progress reports.", meta: "Retained", href: routes.executiveSearch, tag: "Retained" },
  { n: "06", title: "Recruitment Process Outsourcing", desc: "We run all or part of your talent function as an embedded team — your brand, your workflow, our capacity.", meta: "Monthly programme", href: routes.rpo },
  { n: "07", title: "Interim & fractional leadership", desc: "Day-one operators to bridge a transition, lead a turnaround or fill a leadership gap.", meta: "7–14 days", href: routes.interimLeadership },
  { n: "08", title: "Employer of Record", desc: "Hire anywhere, compliantly. We become the legal employer — payroll, tax, benefits and contracts in-country.", meta: "No entity needed", href: routes.employerOfRecord },
] as const;

export const industriesList = [
  { icon: "💻", title: "Technology", desc: "Software engineering, cloud infrastructure, data, cybersecurity, product management and digital transformation from startup to enterprise.", tags: ["Engineering", "Cloud", "Data", "Product"], anchor: "technology" },
  { icon: "🏦", title: "Finance & Banking", desc: "Investment banking, risk, compliance, financial planning, treasury and accounting across global financial institutions and fintech firms.", tags: ["Risk", "Compliance", "FP&A", "Treasury"], anchor: "finance" },
  { icon: "🏥", title: "Healthcare", desc: "Clinical, nursing, allied health, pharmaceutical and healthcare administration across hospitals, clinics and life sciences organisations.", tags: ["Clinical", "Pharma", "Allied Health"], anchor: "healthcare" },
  { icon: "⚖️", title: "Legal", desc: "In-house counsel, solicitors, paralegals, compliance officers and legal operations professionals across corporate and private practice.", tags: ["In-house", "Contracts", "Compliance"], anchor: "legal" },
  { icon: "📈", title: "Sales & Marketing", desc: "B2B and B2C sales, digital marketing, brand, growth, customer success and revenue operations across all markets and company sizes.", tags: ["Sales", "Growth", "Brand", "CX"], anchor: "sales" },
  { icon: "🏭", title: "Operations", desc: "Supply chain, procurement, logistics and operations management for companies scaling their physical or digital operations globally.", tags: ["Supply Chain", "Procurement", "Logistics"], anchor: "supply" },
  { icon: "👥", title: "Human Resources", desc: "HR business partners, talent acquisition, L&D, reward and employee relations from coordinator to CHRO across every industry.", tags: ["HR BP", "TA", "L&D", "Reward"], anchor: "people" },
  { icon: "🏗️", title: "Engineering", desc: "Civil, mechanical, electrical and structural engineering across construction, infrastructure, energy and industrial sectors worldwide.", tags: ["Civil", "Mechanical", "Energy"], anchor: "engineering" },
] as const;

export const clientLogos = [
  { file: "w-hexaware.png", alt: "Hexaware", h: 43 },
  { file: "w-synechron.png", alt: "Synechron", h: 25 },
  { file: "w-saama.png", alt: "Saama", h: 31 },
  { file: "w-infovision.png", alt: "InfoVision", h: 54 },
  { file: "w-genpact.png", alt: "Genpact", h: 35 },
  { file: "w-persistent.png", alt: "Persistent", h: 54 },
  { file: "w-albert-mackenzie.png", alt: "Albert & Mackenzie", h: 20 },
  { file: "w-deutsch-kerrigan.png", alt: "Deutsch Kerrigan", h: 23 },
  { file: "w-vibrantcare.png", alt: "VibrantCare", h: 35 },
  { file: "w-hcl.png", alt: "HCL", h: 15 },
] as const;

/** Offices confirmed real by the client — used for footer/contact/schema. */
export const offices = [
  {
    id: "delaware",
    name: "Delaware (Global HQ)",
    street: "3524 Silverside Rd, Ste 35B",
    city: "Wilmington",
    region: "DE",
    postal: "19810",
    country: "US",
    lat: 39.8168,
    lng: -75.5244,
    desc: "Global headquarters and North American delivery.",
  },
  {
    id: "pune",
    name: "Pune",
    street: "43 Privet Drive, E-Commercial",
    city: "Pune",
    region: "Maharashtra",
    postal: "411045",
    country: "IN",
    lat: 18.5204,
    lng: 73.8567,
    desc: "Central research, sourcing and delivery hub.",
  },
  {
    id: "ontario",
    name: "Ontario",
    street: "373 Vincent Dr",
    city: "Ayr",
    region: "ON",
    postal: "N0B 1E0",
    country: "CA",
    lat: 43.2876,
    lng: -80.3819,
    desc: "Canadian market coverage and cross-border placements.",
  },
] as const;

/** Markets served without a physical office — do not attach addresses or LocalBusiness schema. */
export const servedMarkets = ["United States", "Canada", "UAE", "India"] as const;

/** Order used for the prev/next side page nav — mirrors the original site's page order. */
export const pageOrder: { name: string; href: string }[] = [
  { name: "Home", href: routes.home },
  { name: "Hire Talent", href: routes.hireTalent },
  { name: "Services", href: routes.services },
  { name: "Direct Hire", href: routes.directHire },
  { name: "Contract Staffing", href: routes.contractStaffing },
  { name: "Temporary Staffing", href: routes.temporaryStaffing },
  { name: "RPO", href: routes.rpo },
  { name: "Executive Search", href: routes.executiveSearch },
  { name: "Interim & Fractional Leadership", href: routes.interimLeadership },
  { name: "Employer of Record", href: routes.employerOfRecord },
  { name: "Industries", href: routes.industries },
  { name: "Resources", href: routes.resources },
  { name: "Article", href: routes.article },
  { name: "Case Study", href: routes.caseStudy },
  { name: "About", href: routes.about },
  { name: "Careers", href: routes.career },
  { name: "Search Jobs", href: routes.searchJobs },
  { name: "View Jobs", href: routes.viewJobs },
  { name: "Role", href: routes.role },
  { name: "Open Positions", href: routes.openPositions },
  { name: "Contact", href: routes.contactUs },
  { name: "Sign In", href: routes.signIn },
  { name: "Privacy", href: routes.privacy },
  { name: "Terms", href: routes.terms },
  { name: "Cookies", href: routes.cookies },
];
