export const practices = [
  {
    id: "technology",
    navLabel: "Technology",
    practiceNum: "Practice 01",
    estYear: "est. 2017",
    titleTop: "Technology &",
    titleEm: "engineering leadership.",
    lede: "We've placed engineering leaders into thirty-two of the Fortune-500 tech orgs and forty-plus venture-backed scale-ups. From a first VP of Engineering to a CTO succession.",
    roles: [
      ["VP / SVP of Engineering", "42 placements"],
      ["Chief Technology Officer", "8 placements"],
      ["Director of Platform / SRE", "31 placements"],
      ["Principal / Staff IC tracks", "54 placements"],
      ["Head of Security", "18 placements"],
      ["Head of AI / ML Platform", "22 placements"],
    ],
    partner: { initials: "MW", name: "Marcus Whelan", title: "Partner & Head of Technology Practice · ex-Stripe, Google", creds: ["11 yrs in-practice", "312 mandates"] },
    stats: [
      ["312", "", "Active technology mandates this quarter"],
      ["38", "%", "Outreach reply rate (versus 9% industry baseline)"],
      ["18", "days", "Median time-to-shortlist for VP-level engineering"],
      ["97", "%", "90-day retention on technology placements"],
    ],
    sample: { line: "VP of Platform Engineering at Series C SaaS", sub: "Delaware · 22 days brief-to-offer · $345K base + 0.3% equity" },
  },
  {
    id: "healthcare",
    navLabel: "Healthcare",
    practiceNum: "Practice 02",
    estYear: "est. 2018",
    titleTop: "Healthcare,",
    titleEm: "clinical & biotech.",
    lede: "Provider, payer, and life-sciences senior hires. Our healthcare practice carries the highest credential bar in the firm — every partner has prior operating experience inside a hospital network, payer, or regulated biotech.",
    roles: [
      ["Chief Medical Officer", "14 placements"],
      ["Director of Clinical Operations", "26 placements"],
      ["VP of Regulatory Affairs", "11 placements"],
      ["Head of Quality & 510(k)", "9 placements"],
      ["Chief Nursing Officer", "7 placements"],
    ],
    partner: { initials: "LM", name: "Dr. Lila Mehta", title: "Partner & Head of Healthcare Practice · ex-Mount Sinai, Genentech", creds: ["9 yrs in-practice", "MD · MPH"] },
    stats: [
      ["184", "", "Active healthcare mandates this quarter"],
      ["24", "days", "Median time-to-shortlist for clinical leadership"],
      ["100", "%", "Of clinical placements pre-credentialed at submission"],
      ["94", "%", "12-month retention on physician-leader placements"],
    ],
    sample: { line: "Director of Clinical Operations · UAE hospital network", sub: "Dubai · 31 days · pre-cleared for DHA licensure" },
  },
  {
    id: "legal",
    navLabel: "Legal",
    practiceNum: "Practice 03",
    estYear: "est. 2019",
    titleTop: "Legal &",
    titleEm: "general counsel.",
    lede: "First-GC searches, deputy succession, and lateral partner hires for in-house teams. We've placed counsel into eleven pre-IPO finance teams and twenty-plus growth-stage technology orgs.",
    roles: [
      ["General Counsel", "12 placements"],
      ["Deputy General Counsel", "8 placements"],
      ["Head of Commercial / Privacy", "17 placements"],
      ["Head of Securities & M&A", "5 placements"],
    ],
    partner: { initials: "EP", name: "Eleanor Pritchard", title: "Partner & Head of Legal Practice · ex-Cleary Gottlieb, Stripe", creds: ["JD Yale", "NY & CA bar"] },
    stats: [
      ["92", "", "Active legal mandates this quarter"],
      ["100", "%", "Of finalists licensed in the operating jurisdiction"],
      ["29", "days", "Median time-to-shortlist for GC searches"],
      ["96", "%", "12-month retention on GC placements"],
    ],
    sample: { line: "General Counsel · pre-IPO fintech", sub: "Delaware · 38 days · $420K base + 0.5% equity" },
  },
  {
    id: "finance",
    navLabel: "Finance",
    practiceNum: "Practice 04",
    estYear: "est. 2017",
    titleTop: "Finance, banking",
    titleEm: "capital markets.",
    lede: "CFO succession, treasurer hires, quant teams, and the long bench beneath them. Heavy presence in Delaware, Ontario and Pune — markets where we know the comp committees by name.",
    roles: [
      ["Chief Financial Officer", "16 placements"],
      ["Head of Treasury", "9 placements"],
      ["VP of FP&A", "28 placements"],
      ["Quant Research Lead", "14 placements"],
      ["Head of Risk & Compliance", "22 placements"],
    ],
    partner: { initials: "AB", name: "Anil Bhatia", title: "Partner & Head of Finance Practice · ex-Goldman, BlackRock", creds: ["CFA", "14 yrs in-practice"] },
    stats: [
      ["228", "", "Active finance mandates this quarter"],
      ["19", "days", "Median time-to-shortlist for finance leadership"],
      ["11", "%", "Counter-offer recovery rate (vs. 28% baseline)"],
      ["92", "%", "12-month retention on CFO placements"],
    ],
    sample: { line: "Head of Risk & Compliance · Tier-1 Canadian bank", sub: "Ontario · 27 days · CAD 295K + deferred" },
  },
  {
    id: "aerospace",
    navLabel: "Aerospace & defence",
    practiceNum: "Practice 05",
    estYear: "est. 2020",
    titleTop: "Aerospace,",
    titleEm: "cleared talent.",
    titleMid: "defence &",
    lede: "Tier-1 OEMs, defence primes, and the supplier ecosystem beneath. Eighty-percent of finalists arrive with active clearance — pre-vetted through Rivago's cleared-talent program.",
    roles: [
      ["Director of Manufacturing", "8 placements"],
      ["Principal Systems Engineer", "11 placements"],
      ["Head of FAR/AR & compliance", "4 placements"],
      ["Director, Cleared Cybersecurity", "6 placements"],
    ],
    partner: { initials: "JO", name: "Cmdr. James O'Sullivan (ret.)", title: "Partner & Head of A&D Practice · ex-Lockheed, USN", creds: ["TS/SCI", "20 yrs USN"] },
    stats: [
      ["74", "", "Active aerospace mandates this quarter"],
      ["80", "%", "Of finalists with active TS/SCI at submission"],
      ["42", "days", "Median time-to-shortlist (clearance constraints)"],
      ["100", "%", "Of placements pre-vetted via Rivago cleared program"],
    ],
    sample: { line: "Director of Aerospace Manufacturing · tier-1 supplier", sub: "Delaware · 49 days · $260K + relocation" },
  },
  {
    id: "telecom",
    navLabel: "Telecom",
    practiceNum: "Practice 06",
    estYear: "est. 2019",
    titleTop: "Telecom &",
    titleEm: "network infrastructure.",
    lede: "5G core, fibre rollout, MSO leadership. We staff inside the operator and the supplier — pricing intelligence across both sides of the table.",
    roles: [
      ["Principal Network Architect", "9 placements"],
      ["VP of Network Operations", "6 placements"],
      ["Head of 5G Core Engineering", "4 placements"],
      ["Director, Field Operations", "11 placements"],
    ],
    partner: { initials: "SC", name: "Sarah Chen", title: "Partner & Head of Telecom Practice · ex-Verizon, Ericsson", creds: ["8 yrs in-practice"] },
    stats: [
      ["86", "", "Active telecom mandates this quarter"],
      ["23", "days", "Median time-to-shortlist for network leadership"],
      ["14", "", "Active mandates across operator + supplier sides"],
      ["88", "%", "12-month retention on telecom placements"],
    ],
  },
  {
    id: "automotive",
    navLabel: "Automotive",
    practiceNum: "Practice 07",
    estYear: "est. 2021",
    titleTop: "Automotive &",
    titleEm: "mobility.",
    lede: "OEM, tier-1 supplier, and the new mobility entrants. Battery, ADAS, software-defined vehicle — we know who's hiring and who's quietly looking.",
    roles: [
      ["Director of Manufacturing Engineering", "7 placements"],
      ["Head of Battery Engineering", "4 placements"],
      ["VP of Software (SDV)", "5 placements"],
      ["Head of Supply Quality", "9 placements"],
    ],
    partner: { initials: "VJ", name: "Vikram Joshi", title: "Partner & Head of Automotive Practice · ex-Ford, Rivian", creds: ["P.E.", "13 yrs in-practice"] },
    stats: [
      ["62", "", "Active automotive mandates this quarter"],
      ["28", "days", "Median time-to-shortlist (relocation-heavy)"],
      ["3.4×", "", "Inbound interest per OEM mandate in last 90 days"],
      ["89", "%", "12-month retention on automotive placements"],
    ],
  },
  {
    id: "supply",
    navLabel: "Supply & operations",
    practiceNum: "Practice 08",
    estYear: "est. 2019",
    titleTop: "Supply chain",
    titleEm: "operations.",
    lede: "From distribution-centre leadership to global head-of-supply roles. We staff the spine of the business — the people who keep the operation moving when everything else is on fire.",
    roles: [
      ["Chief Operating Officer", "9 placements"],
      ["VP of Supply Chain", "14 placements"],
      ["Head of Distribution", "11 placements"],
      ["Director, S&OP", "18 placements"],
    ],
    partner: { initials: "DA", name: "Daniel Ahuja", title: "Partner & Head of Supply Practice · ex-Amazon, Maersk", creds: ["MBA Wharton"] },
    stats: [
      ["128", "", "Active supply & ops mandates this quarter"],
      ["22", "days", "Median time-to-shortlist for VP-level supply"],
      ["62", "%", "Of supply placements involve relocation"],
      ["90", "%", "12-month retention on supply placements"],
    ],
  },
  {
    id: "sales",
    navLabel: "Sales & marketing",
    practiceNum: "Practice 09",
    estYear: "est. 2018",
    titleTop: "Sales,",
    titleEm: "growth.",
    titleMid: "marketing &",
    lede: "CRO succession, first-VP-of-marketing hires, demand-gen leadership. We know the OTE patterns and we know which “100% to plan” résumé actually beat the number.",
    roles: [
      ["Chief Revenue Officer", "11 placements"],
      ["VP of Marketing", "19 placements"],
      ["Head of Demand Gen", "22 placements"],
      ["VP of Customer Success", "16 placements"],
    ],
    partner: { initials: "MR", name: "Maya Rasmussen", title: "Partner & Head of GTM Practice · ex-Salesforce, Datadog", creds: ["10 yrs in-practice"] },
    stats: [
      ["204", "", "Active GTM mandates this quarter"],
      ["17", "days", "Median time-to-shortlist for VP+ GTM roles"],
      ["68", "%", "Of CRO finalists beat-plan in their last role"],
      ["89", "%", "12-month retention on CRO placements"],
    ],
  },
  {
    id: "people",
    navLabel: "People & HR",
    practiceNum: "Practice 10",
    estYear: "est. 2018",
    titleTop: "People",
    titleEm: "HR leadership.",
    titleMid: "&",
    lede: "The function that hires our function. CHRO succession, head-of-talent searches, total-rewards leaders. Quietly our most repeat-business practice — once a CHRO trusts you, they bring you with them.",
    roles: [
      ["Chief People Officer", "8 placements"],
      ["VP of Talent Acquisition", "12 placements"],
      ["Head of Total Rewards", "9 placements"],
      ["Director of L&D", "14 placements"],
    ],
    partner: { initials: "AK", name: "Aisha Karim", title: "Partner & Head of People Practice · ex-Airbnb, Unilever", creds: ["SHRM-SCP", "9 yrs in-practice"] },
    stats: [
      ["96", "", "Active people & HR mandates this quarter"],
      ["21", "days", "Median time-to-shortlist for CHRO searches"],
      ["72", "%", "Of mandates come from prior placement referrals"],
      ["93", "%", "12-month retention on CHRO placements"],
    ],
  },
] as const;

export const spine = [
  ["01 · Brief", "Intake call", "Sixty minutes with the hiring manager and the practice partner. We pressure-test the JD, agree must-haves, and write the scorecard before sourcing."],
  ["02 · Map", "Market mapping", "A longlist of 40–80 candidates from the practice partner's network, competitor cap tables, and the Rivago private database."],
  ["03 · Screen", "Calibration interviews", "Forty-five-minute structured screens against your scorecard. First calibration profiles by day twelve. Shortlist hardens by day eighteen."],
  ["04 · Panel", "Loop & debrief", "We project-manage scheduling, debriefs, calibration between rounds, references. Written brief 24 hours before each interview."],
  ["05 · Close", "Offer & care", "Offer negotiation, counter-offer defence, day-90 check-in. Three, six and twelve-month touch-points with both sides."],
] as const;

export const writtenGuarantees = [
  ["21", "days", "Median time-to-shortlist", "From signed JD to three calibrated finalists. Worst case +5 days. We tell you on the kickoff."],
  ["94", "%", "Offer-acceptance rate", "Last twelve months. Cross-practice. Cross-seniority. Counter-offers don't count as accepts."],
  ["12", "mo", "Retained replacement", "Retained placement leaves inside twelve months, we restart the search at no charge. No questions."],
  ["1", "", "Partner on the line", "One named partner from brief to placement. No handoffs. Mobile included. Reachable on a Tuesday at 10pm."],
] as const;

export const practiceTestimonials = [
  {
    practice: "Practice 01 · Technology",
    quote: "Marcus walked into our intake with a list of seven people he'd already had coffee with. Two became finalists. The one we hired closed in twenty-three days against a brief most agencies told us would take ninety.",
    initials: "JS",
    name: "Jamie Sokolov",
    role: "VP of Talent · Series C SaaS",
  },
  {
    practice: "Practice 03 · Legal",
    quote: "Eleanor briefed me on three GC candidates and was honest about which one she'd hire herself. That kind of candour from a search firm is almost extinct. We took her recommendation. She was right.",
    initials: "PB",
    name: "Priya Bhatt",
    role: "CEO · pre-IPO fintech",
  },
  {
    practice: "Practice 02 · Healthcare",
    quote: "Lila understood the DHA licensing path better than my own ops director. Eleven clinical placements, zero compliance issues. We've stopped calling other firms.",
    initials: "SM",
    name: "Samira Mansour",
    role: "CPO · Dubai hospital group",
  },
] as const;
